Repository caddyserver/caddy, pull requests merged in 2019-07, with the labels that each got.

#2663 Flatten HTTP handler config
  modules/caddyhttp/caddyhttp.go
  modules/caddyhttp/encode/encode.go
  modules/caddyhttp/fileserver/staticfiles.go
  modules/caddyhttp/rewrite/rewrite.go
  modules/caddyhttp/routes.go
  modules/caddyhttp/server.go
  modules/caddyhttp/staticresp.go
  modules/caddyhttp/staticresp_test.go
  modules/caddyhttp/templates/templates.go
Labels: Caddy2

#2674 v2: Performance improvements to Replacer implementation (placeholders)
  modules/caddyhttp/replacer.go
  replacer.go
Labels: Caddy2, optimization

#2670 V2: Implement taskkill /f to force quit on windows when caddy stop
  cmd/commands.go
  cmd/proc_posix.go
  cmd/proc_windows.go
Labels: os/windows, v2

#2671 V2:Add stop command to admin.
  admin.go
  sigtrap.go
Labels: v2

#2675 V2: WIP: Tests for Replacer
  replacer.go
  replacer_test.go
Labels: v2
