Repository caddyserver/caddy, pull requests merged in 2020-03, with the labels that each got.

#3111 remove the certificate tag tracking from global state
  caddyconfig/httpcaddyfile/builtins.go
  caddyconfig/httpcaddyfile/directives.go
  caddyconfig/httpcaddyfile/httptype.go
Labels: v2

#3120 v2: http_ntlm: fix panic due to unintialized embedded field
  modules/caddyhttp/reverseproxy/ntlm.go
Labels: v2

#2913 ability to specify that client cert must be present in SSL
  modules/caddytls/connpolicy.go
Labels: v2

#3121 v2: Rework Replacer loop to ignore escaped braces
  replacer.go
  replacer_test.go
Labels: v2

#3128 caddyhttp: New algorithm for auto HTTP->HTTPS redirects
  modules/caddyhttp/autohttps.go
Labels: v2

#3131 Improve global options parsing, plus tests (#3126)
  caddyconfig/httpcaddyfile/httptype_test.go
  caddyconfig/httpcaddyfile/options.go
Labels: v2

#3125 v2: Implement 'pki' app powered by Smallstep for localhost certificates
  caddyconfig/httpcaddyfile/addresses.go
  caddyconfig/httpcaddyfile/addresses_test.go
  caddyconfig/httpcaddyfile/builtins.go
  caddyconfig/httpcaddyfile/httptype.go
  go.mod
  go.sum
  modules/caddyhttp/autohttps.go
  modules/caddyhttp/caddyhttp.go
  modules/caddyhttp/fileserver/command.go
  modules/caddyhttp/reverseproxy/command.go
  modules/caddypki/ca.go
  modules/caddypki/certificates.go
  modules/caddypki/command.go
  modules/caddypki/crypto.go
  modules/caddypki/maintain.go
  modules/caddypki/pki.go
  modules/caddytls/acmeissuer.go
  modules/caddytls/internalissuer.go
  modules/caddytls/tls.go
  modules/standard/import.go
  replacer.go
Labels: in progress, v2

#3141 Fix default sni
  azure-pipelines.yml
  caddyconfig/httpcaddyfile/httptype.go
  caddytest/caddy.localhost.crt
  caddytest/caddy.localhost.key
  caddytest/caddytest.go
  caddytest/caddytest_test.go
  caddytest/integration/caddyfile_test.go
Labels: v2

#3157 Unify strip_prefix, strip_suffix, uri_replace into uri directive
  caddyconfig/httpcaddyfile/directives.go
  modules/caddyhttp/rewrite/caddyfile.go
Labels: v2

#3155 caddyhttp: Implement CEL matcher (see #3051)
  go.mod
  go.sum
  modules/caddyhttp/celmatcher.go
  modules/caddyhttp/matchers.go
Labels: in progress, v2

#3152 Switch to Github Actions
  .github/workflows/ci.yml
  .github/workflows/fuzzing.yml
  azure-pipelines.yml
Labels: under review, v2

#3132 v2: adapter: register config adapters as Caddy modules
  admin.go
  caddyconfig/configadapters.go
  caddyconfig/load.go
Labels: v2
