Repository caddyserver/caddy, pull requests merged in 2020-12, with the labels that each got.

#3895 caddyauth: fix unbuffered channel passed to signal.Notify
  modules/caddyhttp/caddyauth/command.go
Labels: under review

#3901 update quic-go to v0.19.3
  go.mod
  go.sum
Labels: bug

#3739 fastcgi: Set PATH_INFO to file matcher remainder as fallback
  modules/caddyhttp/fileserver/matcher.go
  modules/caddyhttp/fileserver/matcher_test.go
  modules/caddyhttp/reverseproxy/fastcgi/fastcgi.go
Labels: bug

#3932 ci: reject tags if not signed by Matthew Holt's key
  .github/workflows/release.yml
Labels: deployment-ops

#3945 ci: Update goreleaser to fix deprecation notices
  .goreleaser.yml
Labels: deployment-ops

#3941 ci: Add pushing to cloudsmith
  .github/workflows/release.yml
  README.md
Labels: deployment-ops
