Repository caddyserver/caddy, pull requests merged in 2020-06, with the labels that each got.

#3423 caddyfile: Add support for args on imports
  caddyconfig/caddyfile/parse.go
  caddyconfig/caddyfile/parse_test.go
  caddyconfig/caddyfile/testdata/import_args0.txt
  caddyconfig/caddyfile/testdata/import_args1.txt
  caddytest/integration/caddyfile_adapt/import_args_file.txt
  caddytest/integration/caddyfile_adapt/import_args_snippet.txt
  caddytest/integration/testdata/import_respond.txt
Labels: under review

#3465 caddyauth: Cache basicauth results
  modules/caddyhttp/caddyauth/basicauth.go
  modules/caddyhttp/caddyauth/caddyfile.go
Labels: optimization

#3335 httpcaddyfile: Add client certificate config to `tls`
  caddyconfig/httpcaddyfile/builtins.go
  caddytest/caddy.ca.cer
  caddytest/integration/caddyfile_adapt/tls_client_auth_cert_file.txt
  caddytest/integration/caddyfile_adapt/tls_client_auth_inline_cert.txt
  modules/caddytls/connpolicy.go
Labels: under review

#3483 ci: Fix gemfury upload condition, move triggers to publish event
  .github/workflows/release.yml
  .github/workflows/release_published.yml
Labels: deployment-ops

#3463 ci: add CI on s390x
  .github/workflows/ci.yml
Labels: deployment-ops

#3493 ci: skip s390x tests on forks
  .github/workflows/ci.yml
Labels: deployment-ops

#3494 ci: don't run s390x tests on PRs of forks
  .github/workflows/ci.yml
Labels: deployment-ops

#3512 fastcgi: Fix php_fastcgi matcher regression
  caddytest/integration/caddyfile_adapt/php_fastcgi_matcher.txt
  modules/caddyhttp/reverseproxy/fastcgi/caddyfile.go
Labels: bug

#3523 ci: Apparently only single-quote strings are supported
  .github/workflows/release.yml
Labels: bug

#3524 ci: Fix release publish trigger
  .github/workflows/release_published.yml
Labels: bug

#3521 feat: add support for placeholders in query matcher keys & values
  modules/caddyhttp/matchers.go
  modules/caddyhttp/matchers_test.go
Labels: under review
