Repository caddyserver/caddy, pull requests merged in 2020-02, with the labels that each got.

#3005 v2: only compare custom TLS protocol relative to each other if both are set
  modules/caddytls/connpolicy.go
Labels: bug, v2

#3002 Update orig_uri placeholder docs
  modules/caddyhttp/caddyhttp.go
Labels: documentation, v2

#2997 v2: Implement RegExp Var Matcher
  modules/caddyhttp/matchers_test.go
  modules/caddyhttp/vars.go
Labels: v2

#3027 browse: allow filter init via `filter` query param
  modules/caddyhttp/fileserver/browsetpl.go
Labels: v2

#3061 Multiple fixes for header and header_regexp directives
  modules/caddyhttp/matchers.go
  modules/caddyhttp/matchers_test.go
Labels: v2

#3063 Add handler for unhandled errors in errorChain
  modules/caddyhttp/caddyhttp.go
Labels: v2

#2982 v2: Expose TLS placeholders
  caddyconfig/httpcaddyfile/httptype.go
  modules/caddyhttp/caddyhttp.go
  modules/caddyhttp/replacer.go
  modules/caddyhttp/replacer_test.go
  modules/caddyhttp/server.go
  modules/caddytls/values.go
Labels: v2

#3052 v2: debug mode, and 'log' directive for Caddyfile
  caddyconfig/httpcaddyfile/builtins.go
  caddyconfig/httpcaddyfile/httptype.go
  go.mod
  go.sum
  modules/logging/encoders.go
  modules/logging/filewriter.go
  modules/logging/netwriter.go
  replacer.go
  replacer_test.go
Labels: v2

#3047 add global default sni
  caddyconfig/httpcaddyfile/httptype.go
  caddyconfig/httpcaddyfile/options.go
  modules/caddyhttp/caddyhttp.go
Labels: v2

#3082 v2: expand environment variables within caddy files
  caddyconfig/caddyfile/parse.go
Labels: v2

#3103 ci: publish build artifacts
  azure-pipelines.yml
Labels: v2

#3090 cmd: Add `caddy fmt` command.
  caddyconfig/caddyfile/formatter.go
  caddyconfig/caddyfile/formatter_test.go
  cmd/commandfuncs.go
  cmd/commands.go
Labels: v2
