Repository caddyserver/caddy, pull requests merged in 2020-05, with the labels that each got.

#3263 httpcaddyfile: Support single-line matchers
  caddyconfig/httpcaddyfile/httptype.go
  caddyconfig/httpcaddyfile/httptype_test.go
  caddytest/integration/caddyfile_adapt_test.go
Labels: under review

#3267 caddyconfig: Only parse `#` as the start of a comment if preceded by whitespace
  caddyconfig/caddyfile/formatter.go
  caddyconfig/caddyfile/formatter_test.go
  caddyconfig/caddyfile/lexer.go
  caddyconfig/caddyfile/lexer_test.go
Labels: under review

#3344 tls/client auth: verify all certificates in client request
  modules/caddytls/connpolicy.go
Labels: under review

#3373 http: Add support in hash-password for reading from terminals/stdin (#3365)
  modules/caddyhttp/caddyauth/command.go
Labels: under review

#3378 adding wildcard matching of logger names
  modules/caddyhttp/server.go
Labels: under review

#3379 caddyhttp: Fix merging of matchers within a not block
  caddytest/integration/caddyfile_adapt_test.go
  modules/caddyhttp/matchers.go
Labels: bug

#3265 httpcaddyfile: Make global options pluggable
  caddyconfig/httpcaddyfile/directives.go
  caddyconfig/httpcaddyfile/httptype.go
  caddyconfig/httpcaddyfile/options.go
  caddytest/integration/caddyfile_adapt_test.go
Labels: under review

#3315 caddyauth: Add realm support to basicauth Caddyfile directive
  modules/caddyhttp/caddyauth/caddyfile.go
Labels: under review

#3387 windows newline issue withSplitFrontMatter, fix for #3386
  modules/caddyhttp/templates/frontmatter.go
  modules/caddyhttp/templates/tplcontext_test.go
Labels: bug, os/windows

#3284 httpcaddyfile: Add `auto_https` global option
  caddyconfig/httpcaddyfile/httptype.go
  caddyconfig/httpcaddyfile/options.go
  caddytest/integration/caddyfile_adapt/auto_https_disable_redirects.txt
  caddytest/integration/caddyfile_adapt/auto_https_off.txt
Labels: under review

#3431 httpcaddyfile: Improve error on matcher declared outside site block
  caddyconfig/httpcaddyfile/httptype.go
  caddyconfig/httpcaddyfile/httptype_test.go
Labels: under review

#3416 caddyauth: Fix hash-password broken terminal state on SIGINT
  cmd/commandfuncs.go
  cmd/main.go
  modules/caddyhttp/caddyauth/command.go
  modules/caddyhttp/fileserver/command.go
  modules/caddyhttp/reverseproxy/command.go
Labels: bug, under review
