Repository caddyserver/caddy, pull requests merged in 2020-11, with the labels that each got.

#3821 Fixes logging filter for ip_mask with ipv4 adresses
  modules/logging/filters.go
Labels: bug

#3839 caddyhttp: Merge query matchers in Caddyfile
  caddytest/integration/caddyfile_adapt/matcher_syntax.txt
  modules/caddyhttp/matchers.go
Labels: bug

#3861 basicauth: Nitpicks and small improvements
  modules/caddyhttp/caddyauth/basicauth.go
Labels: under review

#3862 caddytls: Support multiple issuers
  caddyconfig/httpcaddyfile/builtins.go
  caddyconfig/httpcaddyfile/tlsapp.go
  caddytest/integration/caddyfile_adapt/global_options.txt
  caddytest/integration/caddyfile_adapt/global_options_acme.txt
  caddytest/integration/caddyfile_adapt/global_options_admin.txt
  caddytest/integration/caddyfile_adapt/tls_automation_policies.txt
  go.mod
  go.sum
  modules/caddyhttp/autohttps.go
  modules/caddytls/acmeissuer.go
  modules/caddytls/automation.go
  modules/caddytls/tls.go
  modules/caddytls/zerosslissuer.go
Labels: help wanted

#3629 reverseproxy: Add Caddyfile scheme shorthand for h2c
  caddytest/integration/caddyfile_adapt/reverse_proxy_h2c_shorthand.txt
  modules/caddyhttp/reverseproxy/caddyfile.go
Labels: under review

#3836 httpcaddyfile: Configure servers via global options
  caddyconfig/httpcaddyfile/addresses.go
  caddyconfig/httpcaddyfile/httptype.go
  caddyconfig/httpcaddyfile/options.go
  caddyconfig/httpcaddyfile/serveroptions.go
  caddytest/integration/caddyfile_adapt/global_server_options_multi.txt
  caddytest/integration/caddyfile_adapt/global_server_options_single.txt
  caddytest/integration/caddyfile_adapt/handle_path.txt
  caddytest/integration/caddyfile_adapt/handle_path_sorting.txt
  caddytest/integration/caddyfile_adapt/import_args_file.txt
  caddytest/integration/caddyfile_adapt/import_args_snippet.txt
  caddytest/integration/caddyfile_adapt/log_filters.txt
  caddytest/integration/caddyfile_adapt/php_fastcgi_expanded_form.txt
  caddytest/integration/caddyfile_adapt/php_fastcgi_matcher.txt
  caddytest/integration/caddyfile_adapt/sort_directives_with_any_matcher_first.txt
  modules/caddyhttp/caddyhttp.go
Labels: under review

#3682 caddyfile: Add support for env var defaults, tests
  caddyconfig/caddyfile/parse.go
  caddyconfig/caddyfile/parse_test.go
Labels: under review

#3874 acme_server: fix reload of acme database
  modules/caddypki/acmeserver/acmeserver.go
  modules/caddypki/ca.go
Labels: under review

#3816 reverseproxy: Avoid "operation was canceled" errors
  modules/caddyhttp/reverseproxy/reverseproxy.go
Labels: bug

#3892 headers: Fix Caddyfile parsing with request matcher
  caddytest/integration/caddyfile_adapt/header.txt
  modules/caddyhttp/headers/caddyfile.go
Labels: bug
