Repository caddyserver/caddy, pull requests merged in 2020-04, with the labels that each got.

#3231 caddytls: Add Caddyfile support for key_type global option
  caddyconfig/httpcaddyfile/httptype.go
  caddyconfig/httpcaddyfile/tlsapp.go
Labels: under review

#3196 Updated custom error page handlers to support more file types
  caddyhttp/errors/errors.go
  caddyhttp/errors/errors_test.go
Labels: v1

#3297 reverseproxy: always set the req.URL.Host with the upstream
  modules/caddyhttp/reverseproxy/reverseproxy.go
Labels: bug

#3300 caddyhttp: Fix common_log format's user ID placeholder
  modules/caddyhttp/server.go
Labels: bug

#3285 refactored caddytest helpers
  caddytest/caddytest.go
  caddytest/integration/caddyfile_test.go
  caddytest/integration/sni_test.go
  caddytest/integration/testdata/cookie.html
Labels: under review

#3302 matcher: Add `split_path` option to file matcher; used in php_fastcgi
  .github/CONTRIBUTING.md
  modules/caddyhttp/fileserver/matcher.go
  modules/caddyhttp/fileserver/matcher_test.go
  modules/caddyhttp/fileserver/testdata/foo.php.php/index.php
  modules/caddyhttp/fileserver/testdata/index.php
  modules/caddyhttp/fileserver/testdata/notphp.php.txt
  modules/caddyhttp/fileserver/testdata/remote.php
  modules/caddyhttp/replacer.go
  modules/caddyhttp/reverseproxy/fastcgi/caddyfile.go
Labels: bug
