Repository caddyserver/caddy, pull requests merged in 2021-11, with the labels that each got.

#4401 caddytls: Mark storage clean timestamp at end of routine
  modules/caddytls/tls.go
Labels: bug, under review

#4387 caddycmd: Add `--keep-backup` to upgrade commands
  cmd/commands.go
  cmd/packagesfuncs.go
  cmd/removebinary.go
  cmd/removebinary_windows.go
Labels: feature

#4407 caddyhttp: Sanitize the path before evaluating path matchers
  modules/caddyhttp/matchers.go
  modules/caddyhttp/matchers_test.go
Labels: bug

#4429 caddyhttp: Log non-500 handler errors at debug level
  modules/caddyhttp/server.go
Labels: feature

#4415 fileserver: Fix handling of symlink sizes in directory listings
  modules/caddyhttp/fileserver/browse.go
  modules/caddyhttp/fileserver/browsetplcontext.go
Labels: bug

#4410 fileserver: browse: do not encode the paths in breadcrumbs and page title
  modules/caddyhttp/fileserver/browsetplcontext.go
  modules/caddyhttp/fileserver/browsetplcontext_test.go
Labels: bug, under review

#4424 logging: add a filter for query parameters
  caddytest/integration/caddyfile_adapt/log_filters.txt
  modules/logging/filters.go
  modules/logging/filters_test.go
Labels: feature, under review

#4425 logging: add a filter for cookies
  caddytest/integration/caddyfile_adapt/log_filters.txt
  modules/logging/filters.go
  modules/logging/filters_test.go
Labels: feature

#4436 reverseproxy: Adjust defaults, document defaults
  caddytest/integration/caddyfile_adapt/reverse_proxy_options.txt
  modules/caddyhttp/reverseproxy/caddyfile.go
  modules/caddyhttp/reverseproxy/fastcgi/fastcgi.go
  modules/caddyhttp/reverseproxy/httptransport.go
  modules/caddyhttp/reverseproxy/reverseproxy.go
Labels: bug, under review, documentation

#4451 caddyfile: make renew_interval option configurable
  caddyconfig/httpcaddyfile/options.go
  caddyconfig/httpcaddyfile/tlsapp.go
  caddytest/integration/caddyfile_adapt/global_options_acme.txt
Labels: feature

#4282 logging: Remove common_log field and single_field encoder (#4149)
  caddyconfig/httpcaddyfile/builtins_test.go
  caddytest/integration/caddyfile_adapt/global_options_log_custom.txt
  modules/caddyhttp/server.go
  modules/logging/encoders.go
Labels: under review

#4452 templates: fix inconsistent nested includes
  modules/caddyhttp/templates/frontmatter_fuzz.go
  modules/caddyhttp/templates/tplcontext.go
  modules/caddyhttp/templates/tplcontext_test.go
Labels: bug

#4453 go.mod: Update to latest smallstep/truststore, support FreeBSD
  go.mod
  go.sum
Labels: upstream
