Repository caddyserver/caddy, pull requests merged in 2021-03, with the labels that each got.

#4046 reverseproxy: Fix upstreams with placeholders with no port
  caddytest/integration/caddyfile_adapt/reverse_proxy_upstream_placeholder.txt
  modules/caddyhttp/reverseproxy/caddyfile.go
Labels: bug

#3991 map: Replace placeholders with regex groups
  caddytest/integration/map_test.go
  modules/caddyhttp/map/map.go
Labels: under review

#4029 logging: add replace filter for static value replacement
  caddytest/integration/caddyfile_adapt/log_filters.txt
  modules/logging/filters.go
Labels: under review

#4070 CONTRIBUTING: fix spelling
  .github/CONTRIBUTING.md
Labels: documentation

#4085 headers: Fix Caddyfile parsing for `request_header` with matchers
  caddytest/integration/caddyfile_adapt/request_header.txt
  modules/caddyhttp/headers/caddyfile.go
Labels: bug

#4050 reverseproxy: Implement health_uri, replaces health_path, supports query
  caddytest/integration/caddyfile_adapt/reverse_proxy_health_path_query.txt
  modules/caddyhttp/reverseproxy/caddyfile.go
  modules/caddyhttp/reverseproxy/healthchecks.go
  modules/caddyhttp/reverseproxy/reverseproxy.go
Labels: under review

#4045 encode: Enhancements to content negotiation, serving precompressed content
  caddytest/integration/caddyfile_adapt/encode_options.txt
  caddytest/integration/caddyfile_adapt/file_server_precompressed.txt
  caddytest/integration/caddyfile_adapt_test.go
  modules/caddyhttp/encode/brotli/brotli_precompressed.go
  modules/caddyhttp/encode/caddyfile.go
  modules/caddyhttp/encode/encode.go
  modules/caddyhttp/encode/encode_test.go
  modules/caddyhttp/encode/gzip/gzip_precompressed.go
  modules/caddyhttp/encode/zstd/zstd_precompressed.go
  modules/caddyhttp/fileserver/caddyfile.go
  modules/caddyhttp/fileserver/staticfiles.go
  modules/caddyhttp/standard/imports.go
Labels: under review

#4096 reverseproxy: Set cookie path to `/` when using cookie lb_policy
  modules/caddyhttp/reverseproxy/selectionpolicies.go
Labels: bug
