Repository caddyserver/caddy, pull requests merged in 2021-09, with the labels that each got.

#4316 cmd: export CaddyVersion(), Commands()
  cmd/commandfuncs.go
  cmd/commands.go
  cmd/main.go
Labels: under review

#4342 fastcgi: Fix Caddyfile parsing when `handle_response` is used
  caddytest/integration/caddyfile_adapt/php_fastcgi_handle_response.txt
  modules/caddyhttp/reverseproxy/fastcgi/caddyfile.go
Labels: bug

#4332 fileserver: properly handle escaped/non-ascii paths
  modules/caddyhttp/caddyhttp.go
  modules/caddyhttp/fileserver/browsetplcontext.go
  modules/caddyhttp/fileserver/matcher_test.go
  modules/caddyhttp/fileserver/staticfiles.go
  modules/caddyhttp/fileserver/testdata/%D9%85%D9%84%D9%81.txt
  modules/caddyhttp/fileserver/testdata/ملف.txt
Labels: bug, under review

#4346 caddyhttp: Add support for triggering errors from `try_files`
  modules/caddyhttp/fileserver/matcher.go
  modules/caddyhttp/matchers.go
  modules/caddyhttp/routes.go
Labels: under review

#4347 fastcgi: Implement `try_files` override in Caddyfile directive
  caddytest/integration/caddyfile_adapt/php_fastcgi_try_files_override.txt
  modules/caddyhttp/reverseproxy/fastcgi/caddyfile.go
Labels: under review

#4321 templates: Add template function "import" to enable {{ template ... }} and {{ block ...}}
  modules/caddyhttp/templates/templates.go
  modules/caddyhttp/templates/tplcontext.go
Labels: under review

#4357 templates: Add tests for funcInclude and funcImport
  modules/caddyhttp/templates/tplcontext_test.go
Labels: under review
