Repository caddyserver/caddy, pull requests merged in 2021-04, with the labels that each got.

#4102 ci: accommodate `go mod` changes of go1.16
  .goreleaser.yml
Labels: deployment-ops

#4103 caddyfile: Normalize line endings before comparing fmt result
  caddyconfig/caddyfile/adapter.go
Labels: bug

#4104 httpcaddyfile: Fix panic in automation policy consolidation
  caddyconfig/httpcaddyfile/tlsapp.go
  caddytest/integration/caddyfile_adapt/tls_automation_policies_4.txt
Labels: bug

#4075 update quic-go to v0.20.0
  go.mod
  go.sum
Labels: under review

#4060 notify: Send all sd_notify signals from main caddy process
  admin.go
  caddy.go
  cmd/commandfuncs.go
  notify/notify.go
  notify/notify_linux.go
  notify/notify_other.go
Labels: under review

#4076 fileserver: Add status code override
  caddytest/integration/caddyfile_adapt/file_server_status.txt
  modules/caddyhttp/fileserver/caddyfile.go
  modules/caddyhttp/fileserver/staticfiles.go
Labels: under review

#4022 caddyfile: reject cyclic imports
  caddyconfig/caddyfile/importgraph.go
  caddyconfig/caddyfile/lexer.go
  caddyconfig/caddyfile/parse.go
  caddyconfig/caddyfile/parse_test.go
  caddyconfig/caddyfile/testdata/import_recursive0.txt
  caddyconfig/caddyfile/testdata/import_recursive1.txt
  caddyconfig/caddyfile/testdata/import_recursive2.txt
  caddyconfig/caddyfile/testdata/import_recursive3.txt
Labels: bug

#4129 caddyfile: Fix `import` replacing unrelated placeholders
  caddyconfig/caddyfile/parse.go
  caddytest/integration/caddyfile_adapt/import_args_snippet_env_placeholder.txt
  replacer.go
Labels: bug

#4132 fileserver: Better handling of HTTP status override
  modules/caddyhttp/fileserver/staticfiles.go
Labels: bug

#4137 caddyhttp: reverseproxy: fix hash selection policy
  modules/caddyhttp/reverseproxy/selectionpolicies.go
  modules/caddyhttp/reverseproxy/selectionpolicies_test.go
Labels: under review

#4128 httpcaddyfile: Fix unexpectedly removed policy
  caddyconfig/httpcaddyfile/tlsapp.go
  caddytest/integration/caddyfile_adapt/tls_automation_policies_5.txt
Labels: bug
