Repository caddyserver/caddy, pull requests merged in 2021-08, with the labels that each got.

#4258 httpcaddyfile: Ensure hosts to skip for logs can always be collected
  caddyconfig/httpcaddyfile/httptype.go
  caddytest/integration/caddyfile_adapt/log_skip_hosts.txt
Labels: bug

#4226 cmd: Implement `add-package` command
  cmd/commandfuncs.go
  cmd/commands.go
  cmd/packagesfuncs.go
Labels: under review

#4274 admin: Synchronize server assignment/references to avoid data race
  admin.go
  admin_test.go
Labels: under review

#4280 feat(time): bring back time.now unix formats
  replacer.go
Labels: under review

#4283 ci: Build and test on Go 1.17, bump minimum to 1.16
  .github/workflows/ci.yml
  .github/workflows/cross-build.yml
  .github/workflows/release.yml
  README.md
  go.mod
Labels: deployment-ops

#4289 cmd: use net.ErrClosed for matching returned error
  cmd/commandfuncs.go
Labels: under review

#4295 caddyhttp: Improved documentation for MatchQuery
  modules/caddyhttp/matchers.go
Labels: documentation

#4297 chore: Update quic-go for go 1.17 support
  go.mod
  go.sum
Labels: under review

#4296 cmd: Fix paths when using an env file
  cmd/main.go
Labels: under review

#4302 caddyfile: Prevent invalid site addresses with comma
  caddyconfig/caddyfile/parse.go
Labels: under review

#4301 caddyfile: Better error message for missing site block braces
  caddyconfig/caddyfile/parse.go
  caddyconfig/httpcaddyfile/httptype.go
Labels: under review

#4299 reverseproxy: Remove redundant flushing
  modules/caddyhttp/reverseproxy/reverseproxy.go
Labels: under review

#4318 encode: ignore flushing until after first write
  modules/caddyhttp/encode/encode.go
Labels: bug

#4319 ci: Only test cross-build on latest Go version
  .github/workflows/cross-build.yml
Labels: deployment-ops
