Repository caddyserver/caddy, pull requests merged in 2021-05, with the labels that each got.

#4093 fileserver: Share template logic for both `templates` and `file_server browse`
  modules/caddyhttp/fileserver/browse.go
  modules/caddyhttp/fileserver/browse_test.go
  modules/caddyhttp/fileserver/browsetplcontext.go
  modules/caddyhttp/fileserver/browsetplcontext_test.go
  modules/caddyhttp/fileserver/staticfiles.go
  modules/caddyhttp/templates/templates.go
  modules/caddyhttp/templates/tplcontext.go
  modules/caddyhttp/templates/tplcontext_test.go
Labels: under review

#4077 httpcaddyfile: Add `auto_https ignore_loaded_certs`
  caddyconfig/httpcaddyfile/builtins.go
  caddyconfig/httpcaddyfile/httptype.go
  caddyconfig/httpcaddyfile/options.go
  caddytest/integration/caddyfile_adapt/auto_https_ignore_loaded_certs.txt
Labels: under review

#4021 reverseproxy: Add `handle_response` blocks to `reverse_proxy` (#3710)
  caddyconfig/httpcaddyfile/directives.go
  caddytest/integration/caddyfile_adapt/reverse_proxy_handle_response.txt
  modules/caddyhttp/encode/caddyfile.go
  modules/caddyhttp/matchers.go
  modules/caddyhttp/matchers_test.go
  modules/caddyhttp/responsematchers.go
  modules/caddyhttp/responsematchers_test.go
  modules/caddyhttp/reverseproxy/caddyfile.go
  modules/caddyhttp/reverseproxy/fastcgi/caddyfile.go
  modules/caddyhttp/reverseproxy/reverseproxy.go
Labels: under review

#4147 fileserver: Fix `file` matcher with empty `try_files`
  modules/caddyhttp/fileserver/matcher.go
Labels: bug

#4131 caddyhttp: Fix fallback for the error handler chain
  modules/caddyhttp/routes.go
Labels: bug

#4164 ci: Run CI on PRs targeting minor version branches
  .github/workflows/ci.yml
  .github/workflows/cross-build.yml
  .github/workflows/lint.yml
Labels: deployment-ops

#4165 reverseproxy: Set the headers in the replacer before `handle_response`
  modules/caddyhttp/reverseproxy/reverseproxy.go
Labels: bug

#4163 caddyfile: Add parse error on site address with trailing `{`
  caddyconfig/caddyfile/parse.go
  caddyconfig/caddyfile/parse_test.go
Labels: bug
