Repository caddyserver/caddy, pull requests merged in 2021-07, with the labels that each got.

#4222 fileserver: Add `disable_canonical_uris` Caddyfile subdirective
  caddytest/integration/caddyfile_adapt/file_server_disable_canonical_uris.txt
  modules/caddyhttp/fileserver/caddyfile.go
Labels: under review

#4236 caddyhttp: Fix incorrect determination of gRPC protocol
  modules/caddyhttp/matchers.go
Labels: bug

#4232 reverseproxy: Keep path to unix socket as dial address
  caddytest/integration/reverseproxy_test.go
  modules/caddyhttp/reverseproxy/healthchecks.go
Labels: bug, under review

#4218 fileserver: Fix browse name_dir_first sorting
  modules/caddyhttp/fileserver/browsetplcontext.go
Labels: bug

#4243 caddyhttp: Fix edgecase with HTTP->HTTPS logic
  caddytest/integration/autohttps_test.go
  modules/caddyhttp/server.go
Labels: bug
