Repository caddyserver/caddy, pull requests merged in 2021-12, with the labels that each got.

#4437 fastcgi: Fix a TODO, prevent zap using reflection for logging env
  modules/caddyhttp/reverseproxy/fastcgi/fastcgi.go
Labels: under review, optimization

#4438 caddyhttp: Make logging of sensitive headers opt-in
  caddyconfig/httpcaddyfile/serveroptions.go
  caddytest/integration/caddyfile_adapt/global_server_options_single.txt
  modules/caddyhttp/marshalers.go
  modules/caddyhttp/push/handler.go
  modules/caddyhttp/reverseproxy/reverseproxy.go
  modules/caddyhttp/server.go
Labels: feature, under review

#4434 logging: add support for hashing data
  caddytest/integration/caddyfile_adapt/log_filters.txt
  modules/logging/filters.go
  modules/logging/filters_test.go
Labels: feature, under review

#4444 improve fmt warning message
  caddyconfig/caddyfile/adapter.go
Labels: documentation

#4475 go.mod: Update smallstep/certificates, no longer need replace
  go.mod
  go.sum
Labels: bug, upstream

#4447 fileserver: do not double-escape paths
  modules/caddyhttp/caddyhttp.go
  modules/caddyhttp/fileserver/browsetplcontext.go
Labels: bug

#4477 httpcaddyfile: Fix sorting edgecase for nested `handle_path`
  caddyconfig/httpcaddyfile/directives.go
  caddyconfig/httpcaddyfile/httptype.go
  caddytest/integration/caddyfile_adapt/sort_directives_within_handle.txt
Labels: bug, under review

#4463 pki: Avoid provisioning the `local` CA when not necessary
  modules/caddypki/acmeserver/acmeserver.go
  modules/caddypki/pki.go
  modules/caddytls/internalissuer.go
Labels: bug

#4433 caddyhttp: Enhance vars matcher
  caddytest/integration/caddyfile_adapt/matcher_syntax.txt
  modules/caddyhttp/vars.go
Labels: feature

#4285 caddyhttp: Implement `http.request.uuid` placeholder
  modules/caddyhttp/app.go
  modules/caddyhttp/replacer.go
Labels: feature, under review

#4485 reverseproxy: Fix incorrect `health_headers` Caddyfile parsing
  caddytest/integration/caddyfile_adapt/reverse_proxy_health_headers.txt
  modules/caddyhttp/reverseproxy/caddyfile.go
Labels: bug, under review

#4499 caddyhttp: Fix `MatchPath` sanitizing
  modules/caddyhttp/matchers.go
Labels: bug, under review
