Repository caddyserver/caddy, pull requests merged in 2022-12, with the labels that each got.

#5229 reverseproxy: Improve hostByHashing distribution
  modules/caddyhttp/reverseproxy/selectionpolicies.go
  modules/caddyhttp/reverseproxy/selectionpolicies_test.go
Labels: bug :lady_beetle:, optimization :chart_with_downwards_trend:

#5248 readme: darker variants of logos in dark mode
  README.md
Labels: documentation :books:

#5210 version: don't panic if read build info doesn't work
  caddy.go
Labels: under review :monocle_face:

#5258 Check for github action updates monthly
  .github/dependabot.yml
Labels: CI/CD :nut_and_bolt:

#5266 ci: exclude dependbot from running tests on s390x machine
  .github/workflows/ci.yml
Labels: CI/CD :nut_and_bolt:

#5271 ci: Update GitHub Actions to avoid `set-output` deprecation
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: CI/CD :nut_and_bolt:

#5270 ci: Fix goreleaser deprecation
  .goreleaser.yml
Labels: CI/CD :nut_and_bolt:
