Repository caddyserver/caddy, pull requests merged in 2022-05, with the labels that each got.

#4754 reverseproxy: Fix Caddyfile support for `replace_status`
  caddytest/integration/caddyfile_adapt/reverse_proxy_handle_response.txt
  modules/caddyhttp/reverseproxy/caddyfile.go
Labels: bug

#4757 templates: Add custom template function registration
  modules/caddyhttp/templates/templates.go
  modules/caddyhttp/templates/tplcontext.go
Labels: feature

#4760 reverseproxy: Permit resolver addresses to not specify a port
  modules/caddyhttp/reverseproxy/upstreams.go
Labels: feature

#4753 caddyfile: Shortcut for `remote_ip` for private IP ranges
  caddytest/integration/caddyfile_adapt/matcher_syntax.txt
  modules/caddyhttp/matchers.go
Labels: feature

#4739 reverseproxy: Support performing pre-check requests
  caddyconfig/httpcaddyfile/builtins.go
  caddyconfig/httpcaddyfile/builtins_test.go
  caddyconfig/httpcaddyfile/directives.go
  caddyconfig/httpcaddyfile/httptype.go
  caddytest/integration/caddyfile_adapt/forward_auth_authelia.txt
  caddytest/integration/caddyfile_adapt/reverse_proxy_options.txt
  modules/caddyhttp/reverseproxy/caddyfile.go
  modules/caddyhttp/reverseproxy/fastcgi/caddyfile.go
  modules/caddyhttp/reverseproxy/forwardauth/caddyfile.go
  modules/caddyhttp/reverseproxy/reverseproxy.go
  modules/caddyhttp/rewrite/rewrite.go
  modules/caddyhttp/rewrite/rewrite_test.go
  modules/caddyhttp/standard/imports.go
Labels: feature

#4657 map: Prevent output destinations overlap with Caddyfile shorthands
  caddyconfig/httpcaddyfile/httptype.go
  modules/caddyhttp/map/caddyfile.go
Labels: bug

#4774 httpcaddyfile: Support multiple values for `default_bind`
  caddyconfig/httpcaddyfile/addresses.go
  caddyconfig/httpcaddyfile/options.go
  caddytest/integration/caddyfile_adapt/global_options_default_bind.txt
Labels: bug

#4778 reverseproxy: Support http1.1>h2c
  modules/caddyhttp/reverseproxy/httptransport.go
Labels: feature

#4796 templates: Documentation consistency
  modules/caddyhttp/templates/templates.go
Labels: documentation

#4798 httpcaddyfile: Add `{err.*}` placeholder shortcut
  caddyconfig/httpcaddyfile/httptype.go
Labels: feature

#4810 minor: micro-optim in run()
  caddy.go
Labels: optimization

#4767 templates: Add `humanize` function
  modules/caddyhttp/templates/templates.go
  modules/caddyhttp/templates/tplcontext.go
  modules/caddyhttp/templates/tplcontext_test.go
Labels: feature, under review

#4811 ci: Fix build caching on Windows
  .github/workflows/ci.yml
  .github/workflows/cross-build.yml
  .github/workflows/release.yml
Labels: CI/CD

#4817 reverseproxy: Add `--internal-certs` CLI flag
  modules/caddyhttp/reverseproxy/command.go
Labels: feature
