Repository caddyserver/caddy, pull requests merged in 2022-03, with the labels that each got.

#4603 Prevent unnecessary loading of config
  caddy.go
Labels: bug

#4300 reverseproxy: Move status replacement intercept to `replace_status`
  caddytest/integration/caddyfile_adapt/reverse_proxy_handle_response.txt
  modules/caddyhttp/reverseproxy/caddyfile.go
Labels: feature

#4549 fileserver: Fix canonicalization redir when within `handle_path`
  modules/caddyhttp/fileserver/browse.go
Labels: bug

#4597 caddyhttp: remote_ip matcher, handling of zone identifiers
  modules/caddyhttp/matchers.go
Labels: bug, under review

#4592 httpcaddyfile: Support explicitly turning off `strict_sni_host`
  caddyconfig/httpcaddyfile/serveroptions.go
  caddytest/integration/caddyfile_adapt/global_server_options_multi.txt
Labels: feature

#4443 pki: Implement `GET /pki/certificates/<id>` API, rework `caddy trust`
  admin.go
  caddy.go
  cmd/commandfuncs.go
  cmd/commands.go
  cmd/main.go
  context.go
  modules/caddypki/adminpki.go
  modules/caddypki/command.go
  modules/caddypki/pki.go
Labels: feature

#4572 fastcgi: ensure `SERVER_PORT` is always set
  modules/caddyhttp/reverseproxy/fastcgi/fastcgi.go
Labels: bug, under review

#4551 reverseproxy: Make shallow-ish clone of the request
  modules/caddyhttp/reverseproxy/reverseproxy.go
Labels: bug

#4606 caddyhttp: Honor wildcard hosts in log SkipHosts
  modules/caddyhttp/server.go
Labels: bug

#4613 fileserver: Add `pass_thru` Caddyfile option
  caddytest/integration/caddyfile_adapt/file_server_pass_thru.txt
  modules/caddyhttp/fileserver/caddyfile.go
Labels: feature

#4616 reverseproxy: Refactor dial address parsing, augment command parsing
  caddyconfig/caddyfile/dispenser.go
  modules/caddyhttp/reverseproxy/addresses.go
  modules/caddyhttp/reverseproxy/caddyfile.go
  modules/caddyhttp/reverseproxy/command.go
Labels: feature

#4507 reverseproxy: Implement trusted proxies for `X-Forwarded-*` headers
  caddytest/integration/caddyfile_adapt/reverse_proxy_trusted_proxies.txt
  modules/caddyhttp/reverseproxy/caddyfile.go
  modules/caddyhttp/reverseproxy/reverseproxy.go
Labels: feature, under review

#4470 reverseproxy: Dynamic upstreams (with support for SRV and A/AAAA lookups)
  caddytest/integration/caddyfile_adapt/reverse_proxy_dynamic_upstreams.txt
  caddytest/integration/caddyfile_adapt/reverse_proxy_options.txt
  modules/caddyhttp/reverseproxy/admin.go
  modules/caddyhttp/reverseproxy/caddyfile.go
  modules/caddyhttp/reverseproxy/healthchecks.go
  modules/caddyhttp/reverseproxy/hosts.go
  modules/caddyhttp/reverseproxy/httptransport.go
  modules/caddyhttp/reverseproxy/reverseproxy.go
  modules/caddyhttp/reverseproxy/selectionpolicies_test.go
  modules/caddyhttp/reverseproxy/upstreams.go
Labels: feature

#4614 fastcgi: Protect against requests with null bytes in the path
  modules/caddyhttp/reverseproxy/fastcgi/fastcgi.go
Labels: bug, under review

#4596 Add a override_domain option to allow DNS challenge delegation
  caddyconfig/httpcaddyfile/builtins.go
  go.mod
  go.sum
  modules/caddytls/acmeissuer.go
  modules/caddytls/automation.go
Labels: feature

#4361 opentelemetry: create a new module
  caddyconfig/httpcaddyfile/directives.go
  caddytest/integration/caddyfile_adapt/tracing.txt
  go.mod
  go.sum
  modules/caddyhttp/standard/imports.go
  modules/caddyhttp/tracing/module.go
  modules/caddyhttp/tracing/module_test.go
  modules/caddyhttp/tracing/tracer.go
  modules/caddyhttp/tracing/tracer_test.go
  modules/caddyhttp/tracing/tracerprovider.go
  modules/caddyhttp/tracing/tracerprovider_test.go
Labels: feature, under review

#4629 caddyhttp: retain all values of vars matcher when specified multiple times
  modules/caddyhttp/vars.go
Labels: bug

#4634 chore: Comment fixes
  caddyconfig/httpcaddyfile/directives.go
  modules/caddyhttp/reverseproxy/caddyfile.go
  modules/caddyhttp/reverseproxy/copyresponse.go
  modules/caddypki/adminapi.go
  modules/caddypki/command.go
Labels: documentation

#4637 ci: Build on Go 1.18, bump actions versions
  .github/workflows/ci.yml
  .github/workflows/cross-build.yml
  .github/workflows/lint.yml
  .github/workflows/release.yml
  caddyconfig/caddyfile/formatter_fuzz.go
  caddyconfig/caddyfile/lexer_fuzz.go
  caddyconfig/httpcaddyfile/addresses_fuzz.go
  duration_fuzz.go
  go.mod
  go.sum
  listeners_fuzz.go
  notify/notify_other.go
  replacer_fuzz.go
  sigtrap_nonposix.go
  sigtrap_posix.go
Labels: CI/CD

#4643 caddyfile: Support for raw token values, improve `map`, `expression`
  caddyconfig/caddyfile/dispenser.go
  caddyconfig/caddyfile/lexer.go
  caddytest/integration/caddyfile_adapt/expression_quotes.txt
  caddytest/integration/caddyfile_adapt/map_with_raw_types.txt
  modules/caddyhttp/celmatcher.go
  modules/caddyhttp/map/caddyfile.go
Labels: bug, under review

#4654 Fix http3 servers dying after reload
  go.mod
  go.sum
  listeners.go
  modules/caddyhttp/app.go
Labels: bug

#4655 caddyfile: Prevent bad block opening tokens
  caddyconfig/caddyfile/dispenser.go
  caddyconfig/caddyfile/parse.go
  caddyconfig/caddyfile/parse_test.go
Labels: bug

#4661 httpcaddyfile: Fix Auto-HTTPS edgecase
  caddyconfig/httpcaddyfile/directives.go
  caddyconfig/httpcaddyfile/httptype.go
  caddyconfig/httpcaddyfile/tlsapp.go
  caddytest/integration/caddyfile_adapt/tls_automation_policies_9.txt
Labels: bug

#4665 chore: Fix for xcaddy builds
  go.mod
  go.sum
Labels: bug, CI/CD
