Repository caddyserver/caddy, pull requests merged in 2022-08, with the labels that each got.

#4870 caddyhttp: Implement `caddy respond` command
  admin.go
  caddy.go
  cmd/main.go
  modules/caddyhttp/app.go
  modules/caddyhttp/fileserver/command.go
  modules/caddyhttp/reverseproxy/command.go
  modules/caddyhttp/server.go
  modules/caddyhttp/staticresp.go
Labels: feature

#4906 httpserver: Configurable shutdown delay
  caddyconfig/httpcaddyfile/httptype.go
  caddyconfig/httpcaddyfile/options.go
  caddytest/integration/caddyfile_adapt/global_options.txt
  listeners.go
  listeners_test.go
  modules/caddyhttp/app.go
  modules/caddyhttp/replacer.go
  modules/caddyhttp/server.go
  usagepool.go
Labels: feature

#4931 cmd: Use newly-available version information
  caddy.go
  cmd/commandfuncs.go
  cmd/main.go
  modules/caddyhttp/reverseproxy/fastcgi/fastcgi.go
  modules/caddyhttp/tracing/tracer.go
Labels: feature

#4930 Replace strings.Index usages with strings.Cut
  caddyconfig/load.go
  cmd/main.go
  listeners.go
  modules.go
  modules/caddyhttp/matchers.go
  modules/caddyhttp/push/link.go
  modules/caddyhttp/reverseproxy/addresses.go
  modules/caddyhttp/reverseproxy/fastcgi/client.go
Labels: optimization

#4932 optimization: Replaced strings.Index with strings.Cut
  cmd/main.go
  modules/caddyhttp/reverseproxy/reverseproxy.go
  modules/caddyhttp/rewrite/rewrite.go
Labels: optimization

#4943 logging: Fix `cookie` filter
  modules/logging/filters.go
  modules/logging/filters_test.go
Labels: bug

#4882 reverseproxy: Support 1xx status codes (HTTP early hints)
  modules/caddyhttp/reverseproxy/reverseproxy.go
Labels: feature

#4951 reverseproxy: Fix H2C dialer using new stdlib `DialTLSContext`
  go.mod
  go.sum
  modules/caddyhttp/reverseproxy/httptransport.go
Labels: bug

#4953 reverseproxy: Add `unix+h2c` Caddyfile network shortcut
  caddytest/integration/caddyfile_adapt/reverse_proxy_h2c_shorthand.txt
  modules/caddyhttp/reverseproxy/addresses.go
Labels: feature

#4707 caddyhttp: Enable HTTP/3 by default
  caddyconfig/httpcaddyfile/serveroptions.go
  caddytest/integration/caddyfile_adapt/global_server_options_single.txt
  go.mod
  go.sum
  listeners.go
  modules/caddyhttp/app.go
  modules/caddyhttp/server.go
  modules/caddytls/connpolicy.go
Labels: under review

#4963 fileserver: reset buffer before using it (#4962)
  modules/caddyhttp/fileserver/browse.go
Labels: bug

#4971 caddyhttp: Set `http.error.message` to the HandlerError message
  modules/caddyhttp/server.go
Labels: bug

#4977 caddyhttp: Fix for nil `handlerErr.Err`
  modules/caddyhttp/server.go
Labels: bug

#4975 templates: cap of slice should not be smaller than length
  modules/caddyhttp/templates/templates.go
Labels: bug

#4981 ci: Increase linter timeout
  .github/workflows/lint.yml
Labels: CI/CD

#4984 events: Begin implementing event system
  context.go
  modules/caddyevent/app.go
  modules/caddyevent/event.go
  modules/caddyevent/listener.go
  modules/caddyevents/app.go
  modules/caddyevents/eventsconfig/caddyfile.go
  modules/caddyevents/exec.go
  modules/caddyhttp/app.go
  modules/caddyhttp/reverseproxy/event.go
  modules/caddyhttp/reverseproxy/healthchecks.go
  modules/caddyhttp/reverseproxy/reverseproxy.go
  modules/caddyhttp/server.go
  modules/caddytls/event.go
  modules/caddytls/tls.go
  modules/standard/imports.go
Labels: under review

#4964 admin: Don't stop old server if new one fails
  admin.go
Labels: bug

#4565 cmd: Migrate to `spf13/cobra`, remove single-dash arg support
  cmd/cobra.go
  cmd/commandfuncs.go
  cmd/commands.go
  cmd/main.go
  go.mod
  go.sum
Labels: under review

#4994 cmd: add completion command
  cmd/commands.go
Labels: feature

#5001 httpcaddyfile: Add `{cookie.*}` placeholder shortcut
  caddyconfig/httpcaddyfile/httptype.go
Labels: feature

#4912 events: Implement event system
  context.go
  go.mod
  go.sum
  modules/caddyevents/app.go
  modules/caddyevents/eventsconfig/caddyfile.go
  modules/caddyhttp/app.go
  modules/caddyhttp/reverseproxy/healthchecks.go
  modules/caddyhttp/reverseproxy/reverseproxy.go
  modules/caddyhttp/server.go
  modules/caddytls/automation.go
  modules/caddytls/tls.go
  modules/standard/imports.go
  usagepool.go
Labels: feature
