Repository caddyserver/caddy, pull requests merged in 2022-01, with the labels that each got.

#4506 headers: Fix `+` in Caddyfile to properly append rather than set
  caddytest/integration/caddyfile_adapt/header.txt
  modules/caddyhttp/headers/caddyfile.go
Labels: bug, under review

#4505 logging: Support turning off roll compression via Caddyfile
  caddytest/integration/caddyfile_adapt/log_roll_days.txt
  modules/logging/filewriter.go
Labels: feature, under review

#4482 reverseproxy, admin: memory leak fix
  caddy.go
  modules/caddyhttp/reverseproxy/reverseproxy.go
Labels: bug, under review

#4313 caddyhttp: Redirect HTTP requests on the HTTPS port to https://
  modules/caddyhttp/app.go
  modules/caddyhttp/httpredirectlistener.go
Labels: under review

#4450 httpcaddyfile: Support configuring `pki` app names via global options
  caddyconfig/httpcaddyfile/pkiapp.go
  caddytest/integration/caddyfile_adapt/global_options_skip_install_trust.txt
Labels: feature, under review

#4522 caddytls: Fix `MatchRemoteIP` provisoning with multiple CIDR ranges
  modules/caddytls/matchers.go
Labels: bug, under review

#4516 rewrite: Fix a double-encode issue when using the `{uri}` placeholder
  modules/caddyhttp/rewrite/rewrite.go
  modules/caddyhttp/rewrite/rewrite_test.go
Labels: bug, under review

#4532 httpcaddyfile: Fix incorrect handling of IPv6 bind addresses
  caddyconfig/httpcaddyfile/addresses.go
  caddytest/integration/caddyfile_adapt/bind_ipv6.txt
Labels: bug

#4531 httpcaddyfile: Add `default_bind` global option
  caddyconfig/httpcaddyfile/addresses.go
  caddyconfig/httpcaddyfile/options.go
  caddytest/integration/caddyfile_adapt/global_options_default_bind.txt
Labels: feature, under review

#4530 caddyhttp: Fix HTTP->HTTPS redir not preferring HTTPS port if ambiguous
  modules/caddyhttp/autohttps.go
Labels: bug, under review

#4528 rewrite: Add `method` Caddyfile directive
  caddyconfig/httpcaddyfile/directives.go
  caddytest/integration/caddyfile_adapt/method_directive.txt
  modules/caddyhttp/rewrite/caddyfile.go
Labels: feature

#4514 httpcaddyfile: Add pki app `root` and `intermediate` cert/key config
  caddyconfig/httpcaddyfile/pkiapp.go
  caddytest/integration/caddyfile_adapt/global_options_skip_install_trust.txt
Labels: feature

#4513 caddytls: Add internal Caddyfile `lifetime`, `sign_with_root` opts
  caddytest/integration/caddyfile_adapt/tls_internal_options.txt
  modules/caddytls/internalissuer.go
Labels: feature

#4535 Improve the reverse-proxy CLI --to flag help message
  modules/caddyhttp/reverseproxy/command.go
Labels: documentation

#4538 caddyhttp: Reject absurd methods
  modules/caddyhttp/server.go
Labels: bug

#4544 caddyhttp: Fix test when /tmp/etc already exists
  modules/caddyhttp/templates/tplcontext_test.go
Labels: bug, CI/CD

#4545 metrics: Enforce smaller set of method labels
  internal/metrics/metrics.go
  internal/metrics/metrics_test.go
  metrics.go
  modules/caddyhttp/metrics.go
Labels: bug
