Repository caddyserver/caddy, pull requests merged in 2022-02, with the labels that each got.

#4550 reverseproxy: Avoid returning a `nil` error during GetClientCertificate
  modules/caddyhttp/reverseproxy/httptransport.go
Labels: bug

#4564 templates: Elaborate on what's supported by the markdown function
  modules/caddyhttp/templates/templates.go
Labels: documentation

#4569 admin: Stop writing 500 status on invalid requests
  admin.go
Labels: bug

#4541 caddytls: Support custom GetCertificate modules (like Tailscale)
  caddyconfig/httpcaddyfile/builtins.go
  caddyconfig/httpcaddyfile/httptype.go
  caddyconfig/httpcaddyfile/options.go
  caddyconfig/httpcaddyfile/tlsapp.go
  go.mod
  go.sum
  modules/caddyhttp/autohttps.go
  modules/caddypki/ca.go
  modules/caddypki/certificates.go
  modules/caddypki/crypto.go
  modules/caddytls/automation.go
  modules/caddytls/certmanagers.go
  modules/caddytls/folderloader.go
Labels: feature

#4589 httpcaddyfile: Disabling OCSP stapling for both managed and unmanaged
  caddyconfig/httpcaddyfile/tlsapp.go
  caddytest/integration/caddyfile_adapt/global_options.txt
Labels: bug

#4587 go.mod: Revert version bump of CEL
  go.mod
  go.sum
Labels: bug, CI/CD

#4584 caddyhttp: Always log handled errors at debug level
  modules/caddyhttp/server.go
Labels: bug

#4583 logging: Add `roll_local_time` Caddyfile option
  caddytest/integration/caddyfile_adapt/log_roll_days.txt
  modules/logging/filewriter.go
Labels: feature

#4582 ci: update goreleaser
  .goreleaser.yml
Labels: under review, CI/CD

#4585 caddyhttp: Move HTTP redirect listener to an optional module
  caddytest/integration/caddyfile_adapt/global_server_options_single.txt
  modules/caddyhttp/app.go
  modules/caddyhttp/httpredirectlistener.go
Labels: bug
