Repository caddyserver/caddy, pull requests merged in 2022-04, with the labels that each got.

#4674 cmd: Fix defaulting admin address if empty in config, fixes `reload`
  cmd/commandfuncs.go
Labels: bug

#4684 logging: Caddyfile support for `duration_format`
  modules/logging/encoders.go
Labels: feature

#4666 reverseproxy: Add `_ms` placeholders for proxy durations
  modules/caddyhttp/app.go
  modules/caddyhttp/replacer.go
  modules/caddyhttp/reverseproxy/reverseproxy.go
  modules/caddyhttp/server.go
Labels: feature

#4695 cmd: Add `--diff` option for `caddy fmt`
  cmd/commandfuncs.go
  cmd/commands.go
Labels: feature

#4700 templates: Switch to `BurntSushi/toml`
  go.mod
  go.sum
  modules/caddyhttp/templates/frontmatter.go
Labels: optimization

#4669 caddypki: Load intermediate for signing on-the-fly
  go.mod
  go.sum
  modules/caddypki/ca.go
Labels: bug

#4703 ci: Ensure we always check for latest version of Go
  .github/workflows/ci.yml
  .github/workflows/cross-build.yml
  .github/workflows/lint.yml
  .github/workflows/release.yml
Labels: CI/CD

#4708 ci: use latest Go version on macOS
  .github/workflows/ci.yml
Labels: CI/CD

#4723 caddytls: Add `propagation_delay`, support `propagation_timeout -1`
  caddytest/integration/caddyfile_adapt/tls_propagation_timeout.txt
  go.mod
  go.sum
  modules/caddytls/acmeissuer.go
  modules/caddytls/automation.go
Labels: feature

#4728 httpcaddyfile: Deprecate paths in site addresses; use zap everywhere
  caddyconfig/caddyfile/parse.go
  caddyconfig/httpcaddyfile/httptype.go
  cmd/commandfuncs.go
  modules/caddyhttp/fileserver/command.go
  modules/caddyhttp/reverseproxy/caddyfile.go
Labels: feature

#4726 httpcaddyfile: Add `{vars.*}` placeholder shortcut, reverse `vars` sort order
  caddyconfig/httpcaddyfile/directives.go
  caddyconfig/httpcaddyfile/httptype.go
  caddytest/integration/caddyfile_adapt/sort_vars_in_reverse.txt
Labels: bug, feature

#4730 caddypki: Fix `caddy trust` command to use the correct API endpoint
  modules/caddypki/command.go
Labels: bug

#4740 caddyhttp: Improve listen addr error message for IPv6
  modules/caddyhttp/autohttps.go
Labels: bug

#4742 cmd: Fix unix socket addresses for admin API requests
  cmd/commandfuncs.go
Labels: bug

#4732 logging: Use `RedirectStdLog`
  .gitignore
  logging.go
Labels: feature

#4746 httpcaddyfile: Fix duplicate access log when debug is on
  caddyconfig/httpcaddyfile/httptype.go
  caddytest/integration/caddyfile_adapt/global_options_debug_with_access_log.txt
Labels: bug
