Repository caddyserver/caddy, pull requests merged in 2022-07, with the labels that each got.

#4867 go.mod: Bump up quic-go to v0.28.0, fixes for BC breaks
  go.mod
  go.sum
  modules/caddyhttp/app.go
Labels: upstream

#4872 reverseproxy: Adjust new TLS Caddyfile directive names
  caddytest/integration/caddyfile_adapt/reverse_proxy_options.txt
  modules/caddyhttp/reverseproxy/caddyfile.go
Labels: feature

#4865 TCP Keepalive configuration
  caddyconfig/httpcaddyfile/serveroptions.go
  listen.go
  listen_linux.go
  modules/caddyhttp/app.go
  modules/caddyhttp/server.go
Labels: under review

#4756 reverseproxy: Implement retry count, alternative to try_duration
  caddytest/integration/caddyfile_adapt/reverse_proxy_load_balance.txt
  modules/caddyhttp/matchers.go
  modules/caddyhttp/reverseproxy/caddyfile.go
  modules/caddyhttp/reverseproxy/reverseproxy.go
Labels: feature

#4900 cmd: Fix reload with stdin
  cmd/commandfuncs.go
  modules/caddypki/command.go
Labels: bug

#4905 reverseproxy: Implement read & write timeouts for HTTP transport
  modules/caddyhttp/reverseproxy/caddyfile.go
  modules/caddyhttp/reverseproxy/httptransport.go
Labels: feature

#4913 ci: Run golangci-lint on multiple os(#4875)
  .github/workflows/lint.yml
Labels: CI/CD

#4916 caddyhttp: Clear out matcher error immediately after grabbing it
  modules/caddyhttp/routes.go
  modules/caddyhttp/vars.go
Labels: bug

#4919 chore: Add .gitattributes to force *.go to LF
  .gitattributes
  .github/workflows/lint.yml
Labels: CI/CD

#4909 fileserver: Support virtual file systems
  modules/caddyhttp/fileserver/browse.go
  modules/caddyhttp/fileserver/browsetplcontext.go
  modules/caddyhttp/fileserver/matcher.go
  modules/caddyhttp/fileserver/matcher_test.go
  modules/caddyhttp/fileserver/staticfiles.go
Labels: feature
