Repository caddyserver/caddy, pull requests merged in 2022-09, with the labels that each got.

#4976 httpcaddyfile: Add shortcut for expression matchers
  caddyconfig/caddyfile/lexer.go
  caddyconfig/httpcaddyfile/httptype.go
  caddytest/integration/caddyfile_adapt/matcher_syntax.txt
Labels: feature

#4990 caddyhttp: Copy logger config to HTTP server during AutoHTTPS
  modules/caddyhttp/autohttps.go
  modules/caddyhttp/server.go
Labels: bug

#5007 dist: deb package manpages and bash completion scripts
  .goreleaser.yml
Labels: feature, CI/CD

#5004 fastcgi: allow users to log stderr output (#4967)
  modules/caddyhttp/reverseproxy/fastcgi/caddyfile.go
  modules/caddyhttp/reverseproxy/fastcgi/client.go
  modules/caddyhttp/reverseproxy/fastcgi/fastcgi.go
Labels: feature

#4972 templates: Document `httpError` function
  modules/caddyhttp/templates/templates.go
Labels: documentation

#4978 fastcgi: Optimize FastCGI transport
  modules/caddyhttp/reverseproxy/fastcgi/client.go
  modules/caddyhttp/reverseproxy/fastcgi/client_test.go
  modules/caddyhttp/reverseproxy/fastcgi/fastcgi.go
  modules/caddyhttp/reverseproxy/fastcgi/header.go
  modules/caddyhttp/reverseproxy/fastcgi/pool.go
  modules/caddyhttp/reverseproxy/fastcgi/reader.go
  modules/caddyhttp/reverseproxy/fastcgi/record.go
  modules/caddyhttp/reverseproxy/fastcgi/writer.go
Labels: under review, optimization

#4910 ci: generate SBOM and sign artifacts using cosign
  .github/workflows/release.yml
  .goreleaser.yml
Labels: under review, CI/CD

#4720 caddyauth: Speed up basicauth provision, deprecate `scrypt`
  modules/caddyhttp/caddyauth/basicauth.go
  modules/caddyhttp/caddyauth/command.go
  modules/caddyhttp/caddyauth/hashes.go
Labels: optimization

#5006 caddyhttp: Support `respond` with HTTP 103 Early Hints
  modules/caddyhttp/matchers.go
  modules/caddyhttp/push/handler.go
  modules/caddyhttp/responsewriter.go
  modules/caddyhttp/staticresp.go
Labels: feature

#4993 fileserver: Support glob expansion in file matcher
  modules/caddyhttp/fileserver/caddyfile.go
  modules/caddyhttp/fileserver/matcher.go
  modules/caddyhttp/fileserver/matcher_test.go
  modules/caddyhttp/fileserver/staticfiles.go
  modules/caddyhttp/fileserver/testdata/foodir/bar.txt
  modules/caddyhttp/replacer.go
  modules/caddyhttp/replacer_test.go
Labels: feature

#5015 httpcaddyfile: Add a couple more placeholder shortcuts
  caddyconfig/httpcaddyfile/httptype.go
Labels: feature

#5022 caddyhttp: ensure ResponseWriterWrapper and ResponseRecorder use ReadFrom if the underlying response writer implements it.
  modules/caddyhttp/responsewriter.go
  modules/caddyhttp/responsewriter_test.go
Labels: optimization

#5027 supplychain: publish signing cert, sbom, and signatures of sbom
  .goreleaser.yml
Labels: CI/CD

#5030 caddyhttp: Explicitly disallow multiple regexp matchers
  modules/caddyhttp/matchers.go
Labels: bug

#4950 httpcaddyfile: Fix bind when IPv6 is specified with network
  caddyconfig/httpcaddyfile/addresses.go
Labels: bug, under review

#4691 caddyhttp: Implement `skip_log` handler
  caddyconfig/httpcaddyfile/builtins.go
  caddyconfig/httpcaddyfile/directives.go
  caddytest/integration/caddyfile_adapt/log_except_catchall_blocks.txt
  modules/caddyhttp/logging.go
  modules/caddyhttp/server.go
Labels: feature

#4693 feat: Multiple 'to' upstreams in reverse-proxy cmd
  modules/caddyhttp/reverseproxy/command.go
Labels: feature

#5043 caddyhttp: Honor grace period in background
  caddy.go
  caddytest/caddytest.go
  caddytest/integration/caddyfile_test.go
  caddytest/integration/handler_test.go
  caddytest/integration/map_test.go
  caddytest/integration/reverseproxy_test.go
  caddytest/integration/sni_test.go
  caddytest/integration/stream_test.go
  modules/caddyhttp/app.go
Labels: optimization

#5051 caddyhttp: Skip inserting HTTP->HTTPS redir if catch-all for both exist
  modules/caddyhttp/autohttps.go
Labels: bug

#5054 httpcaddyfile: Fix `protocols` global option parsing
  admin_test.go
  caddyconfig/httpcaddyfile/serveroptions.go
  caddytest/integration/caddyfile_adapt/global_server_options_single.txt
Labels: bug

#5060 encode: don't WriteHeader unless called
  modules/caddyhttp/encode/encode.go
Labels: bug

#5063 Reuse unix sockets (UDS) and don't try to serve HTTP/3 over UDS
  listen.go
  listen_linux.go
  listen_unix.go
  modules/caddyhttp/app.go
Labels: bug

#5067 ci: extend goreleaser timeout to 1-hour
  .github/workflows/release.yml
Labels: CI/CD

#5079 ci: fix integration tests
  caddytest/caddytest.go
  caddytest/integration/autohttps_test.go
  caddytest/integration/caddyfile_test.go
  caddytest/integration/handler_test.go
  caddytest/integration/map_test.go
  caddytest/integration/reverseproxy_test.go
  caddytest/integration/sni_test.go
  caddytest/integration/stream_test.go
  caddytest/integration/test.init.config
Labels: CI/CD

#5088 reverseproxy: fix upstream scheme handling
  modules/caddyhttp/reverseproxy/command.go
Labels: bug
