Repository caddyserver/caddy, pull requests merged in 2022-06, with the labels that each got.

#4389 caddytls: Make peer certificate verification pluggable
  modules/caddytls/connpolicy.go
Labels: feature

#4784 Add renegotiation option in reverseproxy tls client
  caddytest/integration/caddyfile_adapt/reverse_proxy_options.txt
  modules/caddyhttp/reverseproxy/caddyfile.go
  modules/caddyhttp/reverseproxy/httptransport.go
Labels: feature

#4831 headers: Support wildcards for delete ops
  modules/caddyhttp/headers/headers.go
  modules/caddyhttp/headers/headers_test.go
Labels: feature

#4783 forwardauth: Support renaming copied headers, block support
  caddytest/integration/caddyfile_adapt/forward_auth_rename_headers.txt
  modules/caddyhttp/reverseproxy/forwardauth/caddyfile.go
Labels: feature

#4843 Add SkipTLSPorts to http transport
  caddytest/integration/caddyfile_adapt/reverse_proxy_options.txt
  modules/caddyhttp/reverseproxy/caddyfile.go
  modules/caddyhttp/reverseproxy/httptransport.go
Labels: feature, under review

#4856 forwardauth: Fix case when `copy_headers` is omitted
  modules/caddyhttp/reverseproxy/forwardauth/caddyfile.go
Labels: bug

#4846 admin: Implement /adapt endpoint (close #4465)
  caddyconfig/load.go
Labels: feature
