Repository caddyserver/caddy, pull requests merged in 2022-10, with the labels that each got.

#5105 fileserver: better dark mode visited link contrast
  modules/caddyhttp/fileserver/browse.html
Labels: bug

#5106 Fix inverted logic in Windows service detection
  service_windows.go
Labels: bug

#5118 ci: enhance the CI/CD flow
  .github/workflows/ci.yml
  .goreleaser.yml
Labels: CI/CD

#5110 httpcaddyfile: Fix edgecase with `auto_https off` with provided certs
  caddyconfig/httpcaddyfile/tlsapp.go
  caddytest/integration/caddyfile_adapt/tls_automation_policies_10.txt
Labels: bug

#5109 logging: Better `console` encoder defaults
  modules/logging/encoders.go
Labels: bug

#5099 treat invalid file path as notFound
  modules/caddyhttp/fileserver/staticfiles.go
Labels: needs info

#5108 logging: Add `time_local` option to use local time instead of UTC
  modules/logging/encoders.go
Labels: feature

#5101 logging: Perform filtering on arrays of strings (where possible)
  modules/logging/filters.go
  modules/logging/filters_test.go
Labels: bug

#5097 forwardauth: Canonicalize header fields (fix #5038)
  modules/caddyhttp/reverseproxy/forwardauth/caddyfile.go
Labels: bug

#5077 httploader: Implement retries
  caddyconfig/httploader.go
Labels: feature

#5127 replacer: working directory global placeholder
  replacer.go
  replacer_test.go
Labels: feature

#5131 fileserver: stop listing dir when request context is cancelled
  modules/caddyhttp/fileserver/browse.go
  modules/caddyhttp/fileserver/browsetplcontext.go
Labels: under review, optimization

#5149 docs: Fix templates documentation, stray newline breaks godoc
  modules/caddyhttp/templates/templates.go
Labels: documentation

#5148 fileserver: Reject ADS and short name paths; trim trailing dots and spaces on Windows
  modules/caddyhttp/caddyhttp_test.go
  modules/caddyhttp/fileserver/staticfiles.go
Labels: bug, os/windows

#5161 caddyhttp: add placeholder {http.request.orig_uri.path.*}
  modules/caddyhttp/replacer.go
Labels: feature

#5159 caddyconfig: fix httploader leak from unused responses due to loop not breaking on success
  caddyconfig/httploader.go
Labels: bug

#5160 caddytest: Increased sleep between retries to reduce flakey tests in CI
  caddytest/caddytest.go
Labels: CI/CD

#5176 caddyhttp: Canonicalize header field names
  modules/caddyhttp/staticresp.go
Labels: bug
