Repository caddyserver/caddy, pull requests merged in 2023-07, with the labels that each got.

#5623 caddytls: Reuse certificate cache through reloads
  admin.go
  caddy.go
  context.go
  go.mod
  go.sum
  modules/caddyhttp/autohttps.go
  modules/caddyhttp/reverseproxy/httptransport.go
  modules/caddypki/adminapi.go
  modules/caddytls/automation.go
  modules/caddytls/tls.go
Labels: optimization :chart_with_downwards_trend:

#5626 caddyfile: Fix comparing if two tokens are on the same line
  caddyconfig/caddyfile/dispenser.go
  caddyconfig/caddyfile/lexer.go
  caddyconfig/caddyfile/parse.go
  caddyconfig/httpcaddyfile/builtins_test.go
Labels: bug :lady_beetle:

#5630 fileserver: add `export-template` sub-command to `file-server`
  modules/caddyhttp/fileserver/command.go
Labels: feature :gear:

#5636 chore: update quic-go to v0.36.2
  go.mod
  go.sum
Labels: dependencies

#5645 core: Refine mutex during reloads (fix #5628)
  admin.go
  caddy.go
  context.go
Labels: bug :lady_beetle:

#5644 Update quic-go to v0.37.0, bump to Go 1.20 minimum
  .github/workflows/ci.yml
  .github/workflows/cross-build.yml
  .github/workflows/lint.yml
  .github/workflows/release.yml
  .github/workflows/release_published.yml
  README.md
  go.mod
  go.sum
  modules/caddyhttp/caddyauth/basicauth.go
  modules/caddyhttp/errors.go
  modules/caddyhttp/fileserver/staticfiles.go
  modules/caddyhttp/reverseproxy/reverseproxy.go
  modules/caddyhttp/reverseproxy/selectionpolicies.go
Labels: dependencies :chains:
