Repository caddyserver/caddy, pull requests merged in 2023-12, with the labels that each got.

#5963 tls: accept placeholders in string values of certificate loaders
  modules/caddytls/fileloader.go
  modules/caddytls/folderloader.go
  modules/caddytls/pemloader.go
  modules/caddytls/storageloader.go
Labels: feature :gear:

#5915 proxyprotocol: use github.com/pires/go-proxyproto
  go.mod
  go.sum
  modules/caddyhttp/proxyprotocol/listenerwrapper.go
  modules/caddyhttp/proxyprotocol/module.go
  modules/caddyhttp/proxyprotocol/policy.go
  modules/caddyhttp/reverseproxy/httptransport.go
Labels: under review :monocle_face:, dependencies :chains:

#5859 caddyhttp: Add `uuid` to access logs when used
  caddyconfig/httpcaddyfile/shorthands.go
  modules/caddyhttp/logging.go
  modules/caddyhttp/replacer.go
Labels: feature :gear:

#5880 fileserver: Add `precompressed` flag to command
  modules/caddyhttp/fileserver/command.go
Labels: feature :gear:

#5855 fileserver: Enable compression for command by default
  modules/caddyhttp/fileserver/command.go
Labels: feature :gear:

#5979 metrics: Record request metrics on HTTP errors
  modules/caddyhttp/metrics.go
  modules/caddyhttp/metrics_test.go
Labels: bug :lady_beetle:

#5944 logging: Add `zap.Option` support
  logging.go
  modules/caddyhttp/reverseproxy/streaming.go
Labels: feature :gear:

#5711 feat: use automaxprocs for better perf in containers
  cmd/caddy/main.go
  go.mod
  go.sum
Labels: optimization :chart_with_downwards_trend:

#5997 httpcaddyfile: Fix cert file decoding to load multiple PEM in one file
  caddyconfig/httpcaddyfile/builtins.go
Labels: bug :lady_beetle:
