Repository caddyserver/caddy, pull requests merged in 2023-04, with the labels that each got.

#5475 fileserver: Add color-scheme meta tag
  modules/caddyhttp/fileserver/browse.html
Labels: bug :lady_beetle:

#5466 Update contributing guidelines
  .github/CONTRIBUTING.md
Labels: discussion :speech_balloon:

#5437 cmd: Support ' quotes in envfile parsing
  cmd/main.go
Labels: feature :gear:

#5495 chore: Adjustments to CI caching
  .github/workflows/ci.yml
  .github/workflows/cross-build.yml
  .github/workflows/release.yml
Labels: CI/CD :nut_and_bolt:

#5492 celmatcher: Implement `pkix.Name` conversion to string
  modules/caddyhttp/celmatcher.go
Labels: bug :lady_beetle:

#5505 caddyfile: Stricter parsing, error for brace on new line
  caddyconfig/caddyfile/parse.go
  caddyconfig/caddyfile/parse_test.go
  modules/caddyhttp/reverseproxy/caddyfile.go
  modules/caddyhttp/reverseproxy/fastcgi/caddyfile.go
  modules/caddyhttp/reverseproxy/forwardauth/caddyfile.go
Labels: bug :lady_beetle:

#5497 templates: Add `fileStat` function
  modules/caddyhttp/templates/tplcontext.go
Labels: feature :gear:

#5498 reverseproxy: Fix reinitialize upstream healthy metrics
  modules/caddyhttp/reverseproxy/metrics.go
Labels: bug :lady_beetle:

#5509 caddyhttp: Impl `ResponseWriter.Unwrap()`, prep for Go 1.20's `ResponseController`
  metrics.go
  modules/caddyhttp/encode/encode.go
  modules/caddyhttp/fileserver/staticfiles.go
  modules/caddyhttp/responsewriter.go
  modules/caddyhttp/responsewriter_test.go
Labels: feature :gear:

#5507 logging: Add traceID field to access logs when tracing is active
  go.mod
  go.sum
  modules/caddyhttp/logging.go
  modules/caddyhttp/reverseproxy/fastcgi/fastcgi.go
  modules/caddyhttp/server.go
  modules/caddyhttp/server_test.go
  modules/caddyhttp/tracing/tracer.go
Labels: feature :gear:, discussion :speech_balloon:
