Repository caddyserver/caddy, pull requests merged in 2023-03, with the labels that each got.

#5413 core: Eliminate unnecessary shutdown delay on Unix
  go.mod
  listen.go
  listen_unix.go
  modules/caddyhttp/app.go
Labels: bug :lady_beetle:

#5147 Support for OTEL_PROPAGATORS environment variable
  go.sum
  modules/caddyhttp/tracing/tracer.go
Labels: under review :monocle_face:

#5427 fileserver: New file browse template
  modules/caddyhttp/fileserver/browse.go
  modules/caddyhttp/fileserver/browse.html
  modules/caddyhttp/fileserver/browsetplcontext.go
Labels: feature :gear:

#5435 reverseproxy: Reset Content-Length to prevent fastcgi from hanging
  modules/caddyhttp/reverseproxy/reverseproxy.go
Labels: bug :lady_beetle:

#5440 cicd: add `--yes` to cosign arguments
  .goreleaser.yml
Labels: CI/CD :nut_and_bolt:

#5443 caddytls: Zero out throttle window first
  modules/caddytls/automation.go
  modules/caddytls/tls.go
Labels: bug :lady_beetle:

#5104 caddyhttp: Determine real client IP if trusted proxies configured
  caddyconfig/httpcaddyfile/httptype.go
  caddyconfig/httpcaddyfile/serveroptions.go
  caddytest/integration/caddyfile_adapt/global_server_options_single.txt
  caddytest/integration/caddyfile_adapt/matcher_syntax.txt
  modules/caddyhttp/app.go
  modules/caddyhttp/ip_matchers.go
  modules/caddyhttp/marshalers.go
  modules/caddyhttp/matchers.go
  modules/caddyhttp/server.go
Labels: feature :gear:

#5460 reverseproxy: Header up/down support for CLI command
  modules/caddyhttp/reverseproxy/command.go
Labels: feature :gear:

#5458 replacer: Add HTTP time format
  replacer.go
Labels: feature :gear:

#5459 caddytls: Run the replacer on automation policy subjects
  caddyconfig/httpcaddyfile/tlsapp.go
  caddyconfig/httpcaddyfile/tlsapp_test.go
  modules/caddyhttp/autohttps.go
  modules/caddyhttp/reverseproxy/command.go
  modules/caddytls/automation.go
  modules/caddytls/tls.go
Labels: feature :gear:

#5441 log: make `sink` encodable
  caddyconfig/httpcaddyfile/httptype.go
  logging.go
  modules/caddyhttp/fileserver/command.go
  modules/caddyhttp/reverseproxy/command.go
  modules/caddyhttp/staticresp.go
Labels: feature :gear:, needs docs :writing_hand:

#5461 caddyhttp: Log request body bytes read
  modules/caddyhttp/server.go
Labels: feature :gear:

#5472 reverseproxy: Add mention of which half a copyBuffer err comes from
  modules/caddyhttp/reverseproxy/streaming.go
Labels: feature :gear:

#5424 proxyprotocol: Add PROXY protocol support to `reverse_proxy`, add HTTP listener wrapper
  go.mod
  go.sum
  modules/caddyhttp/proxyprotocol/listenerwrapper.go
  modules/caddyhttp/proxyprotocol/module.go
  modules/caddyhttp/reverseproxy/caddyfile.go
  modules/caddyhttp/reverseproxy/hosts.go
  modules/caddyhttp/reverseproxy/httptransport.go
  modules/caddyhttp/reverseproxy/reverseproxy.go
  modules/caddyhttp/standard/imports.go
Labels: feature :gear:
