Repository caddyserver/caddy, pull requests merged in 2023-10, with the labels that each got.

#5780 reverseproxy: Allow fallthrough for response handlers without routes
  modules/caddyhttp/reverseproxy/reverseproxy.go
Labels: bug :lady_beetle:

#5845 templates: Add dummy `RemoteAddr` to `httpInclude` request, proxy compatibility
  modules/caddyhttp/templates/tplcontext.go
Labels: bug :lady_beetle:

#5808 httpcaddyfile: Enable TLS for catch-all site if `tls` directive is specified
  caddyconfig/httpcaddyfile/httptype.go
  caddytest/integration/caddyfile_adapt/enable_tls_for_catch_all_site.txt
Labels: bug :lady_beetle:

#5841 reverseproxy: Fix retries on "upstreams unavailable" error
  modules/caddyhttp/reverseproxy/reverseproxy.go
Labels: bug :lady_beetle:

#5828 reverseproxy: fix parsing Caddyfile fails for unlimited request/response buffers
  caddytest/integration/caddyfile_adapt/reverse_proxy_buffers.txt
  modules/caddyhttp/reverseproxy/caddyfile.go
Labels: bug :lady_beetle:

#5874 cmd: Fix exiting with custom status code, add `caddy -v`
  .gitignore
  cmd/cobra.go
  cmd/commandfuncs.go
  cmd/commands.go
  cmd/main.go
Labels: bug :lady_beetle:

#5860 httpcaddyfile: Sort TLS SNI matcher, for deterministic adapt output
  caddyconfig/httpcaddyfile/httptype.go
Labels: bug :lady_beetle:

#5862 reverseproxy: Fix `least_conn` policy regression
  modules/caddyhttp/reverseproxy/selectionpolicies.go
Labels: bug :lady_beetle:

#5793 reverseproxy: Add more debug logs
  modules/caddyhttp/reverseproxy/caddyfile.go
  modules/caddyhttp/reverseproxy/reverseproxy.go
  modules/caddyhttp/reverseproxy/streaming.go
  modules/caddyhttp/reverseproxy/streaming_test.go
Labels: feature :gear:

#5852 tls: Add support for X25519Kyber768Draft00 post-quantum "curve" when compiled with cfgo.
  modules/caddytls/cf.go
Labels: feature :gear:, upstream :arrow_up:

#5867 fileserver: Add canonical URL to browse template
  modules/caddyhttp/fileserver/browse.html
Labels: bug :lady_beetle:

#5870 admin: respond with 4xx status code on non-existing config path
  admin.go
  admin_test.go
Labels: bug :lady_beetle:

#5883 caddyfile: Fix variadic placeholder false positive when token contains `:`
  caddyconfig/caddyfile/importargs.go
  caddyconfig/caddyfile/parse_test.go
Labels: bug :lady_beetle:

#5891 cmd: upgrade: resolve symlink of the executable
  cmd/packagesfuncs.go
Labels: bug :lady_beetle:

#5896 httpcaddyfile: Fix TLS automation policy merging with get_certificate
  caddyconfig/httpcaddyfile/tlsapp.go
  caddytest/integration/caddyfile_adapt/tls_automation_policies_11.txt
Labels: bug :lady_beetle:

#5898 templates: Clarify `include` args docs, add `.ClientIP`
  modules/caddyhttp/templates/templates.go
  modules/caddyhttp/templates/tplcontext.go
Labels: documentation :books:

#5848 Use sync.Pool to reduce lengthReader allocations
  modules/caddyhttp/server.go
Labels: optimization :chart_with_downwards_trend:

#5725 core: Apply SO_REUSEPORT to UDP sockets
  listen.go
  listen_unix.go
  listeners.go
Labels: bug :lady_beetle:

#5881 httpcaddyfile: Remove port from logger names
  caddyconfig/httpcaddyfile/httptype.go
  caddytest/integration/caddyfile_adapt/log_except_catchall_blocks.txt
  caddytest/integration/caddyfile_adapt/log_override_hostname.txt
  caddytest/integration/caddyfile_adapt/log_override_name_multiaccess.txt
  caddytest/integration/caddyfile_adapt/log_override_name_multiaccess_debug.txt
Labels: bug :lady_beetle:

#5905 templates: Delete headers on `httpError` to reset to clean slate
  modules/caddyhttp/templates/tplcontext.go
Labels: bug :lady_beetle:

#5908 go.mod: CVE-2023-45142 Update opentelemetry
  go.mod
  go.sum
Labels: dependencies :chains:

#5910 caddyhttp: Adjust `scheme` placeholder docs
  modules/caddyhttp/app.go
Labels: documentation :books:

#5916 chore: Fix usage pool comment
  usagepool.go
Labels: documentation :books:

#5922 go.mod: update quic-go version to v0.40.0
  go.mod
  go.sum
Labels: dependencies :chains:
