Repository caddyserver/caddy, pull requests merged in 2023-06, with the labels that each got.

#5532 cmd: Implement storage import/export
  cmd/commands.go
  cmd/storagefuncs.go
Labels: feature :gear:

#5573 caddyhttp: support custom network for HTTP/3
  modules/caddyhttp/server.go
Labels: feature :gear:

#5574 headers: Allow `>` defer shortcut for replacements
  caddytest/integration/caddyfile_adapt/header.txt
  modules/caddyhttp/headers/caddyfile.go
Labels: feature :gear:

#5567 reverseproxy: streaming timeouts
  modules/caddyhttp/reverseproxy/caddyfile.go
  modules/caddyhttp/reverseproxy/reverseproxy.go
  modules/caddyhttp/reverseproxy/streaming.go
Labels: feature :gear:

#5579 reverseproxy: Implement `weighted_round_robin` load balancing policy
  caddytest/integration/caddyfile_adapt/reverse_proxy_load_balance_wrr.txt
  modules/caddyhttp/reverseproxy/selectionpolicies.go
  modules/caddyhttp/reverseproxy/selectionpolicies_test.go
Labels: feature :gear:

#5584 go.mod: Update quic-go to v0.36.0
  go.mod
  go.sum
Labels: dependencies

#5591 reverseproxy: Support `tls_except_ports` for active health checks
  modules/caddyhttp/reverseproxy/healthchecks.go
Labels: bug :lady_beetle:

#4741 core: Add optional unix socket file permissions
  listeners.go
  listeners_test.go
Labels: feature :gear:

#5596 core: Skip `chmod` for abstract unix sockets
  listeners.go
Labels: bug :lady_beetle:

#5608 chore: remove deprecated property `rlcp` in goreleaser config
  .goreleaser.yml
Labels: CI/CD :nut_and_bolt:

#5606 listeners: embed `net.UDPConn` to allow automatic optimization by quic-go
  listeners.go
Labels: bug :lady_beetle:
