Repository caddyserver/caddy, pull requests merged in 2023-01, with the labels that each got.

#5287 caddytls: Add `dns_ttl` config, improve Caddyfile `tls` options
  caddyconfig/httpcaddyfile/builtins.go
  caddytest/integration/caddyfile_adapt/tls_dns_ttl.txt
  modules/caddytls/acmeissuer.go
Labels: feature :gear:

#5284 reverseproxy: Set origreq in active health check
  modules/caddyhttp/reverseproxy/healthchecks.go
Labels: bug :lady_beetle:

#5269 reverseproxy: Don't enable auto-https when `--from` flag is http
  modules/caddyhttp/reverseproxy/command.go
Labels: bug :lady_beetle:

#5289 Fix hanging caused by Transfer-Encoding: chunked
  modules/caddyhttp/reverseproxy/reverseproxy.go
Labels: bug :lady_beetle:

#5103 caddyhttp: Add server-level `trusted_proxies` config
  caddyconfig/httpcaddyfile/serveroptions.go
  caddytest/integration/caddyfile_adapt/global_server_options_single.txt
  modules/caddyhttp/app.go
  modules/caddyhttp/matchers.go
  modules/caddyhttp/replacer.go
  modules/caddyhttp/reverseproxy/caddyfile.go
  modules/caddyhttp/reverseproxy/reverseproxy.go
  modules/caddyhttp/server.go
Labels: feature :gear:

#5314 go.mod: Update golang.org/x/net to v0.5.0
  go.mod
  go.sum
Labels: upstream :arrow_up:

#5315 httpcaddyfile: Fix `handle` grouping inside `route`
  caddyconfig/httpcaddyfile/builtins.go
  caddyconfig/httpcaddyfile/directives.go
  caddyconfig/httpcaddyfile/httptype.go
  caddytest/integration/caddyfile_adapt/handle_nested_in_route.txt
  caddytest/integration/caddyfile_adapt/php_fastcgi_expanded_form.txt
Labels: bug :lady_beetle:

#5325 chore: Fix typo, coral -> cobra
  cmd/cobra.go
  cmd/commands.go
Labels: bug :lady_beetle:

#5320 httpcaddyfile: Ignore the import empty dotfile.
  caddyconfig/caddyfile/parse.go
  caddyconfig/caddyfile/parse_test.go
  caddyconfig/caddyfile/testdata/empty.txt
  caddyconfig/caddyfile/testdata/glob/.dotfile.txt
  caddyconfig/caddyfile/testdata/glob/import_test1.txt
  caddyconfig/caddyfile/testdata/only_white_space.txt
Labels: feature :gear:, under review :monocle_face:

#5297 cmd: `caddy fmt` return code is 1 if not formatted
  caddyconfig/caddyfile/adapter.go
  cmd/commandfuncs.go
Labels: feature :gear:

#5329 tracing: Support placeholders in span name
  modules/caddyhttp/tracing/module_test.go
  modules/caddyhttp/tracing/tracer.go
Labels: feature :gear:

#5330 reverseproxy: Add flag to short command to disable redirects
  modules/caddyhttp/reverseproxy/command.go
Labels: feature :gear:

#5323 caddyfile: Allow overriding server names
  caddyconfig/httpcaddyfile/httptype.go
  caddyconfig/httpcaddyfile/serveroptions.go
  caddytest/integration/caddyfile_adapt/server_names.txt
Labels: feature :gear:

#5339 httpcaddyfile: Add persist_config global option
  caddyconfig/httpcaddyfile/httptype.go
  caddyconfig/httpcaddyfile/options.go
  caddytest/integration/caddyfile_adapt/global_options_admin_with_persist_config_off.txt
  caddytest/integration/caddyfile_adapt/global_options_persist_config.txt
Labels: feature :gear:

#5351 cmd: `fmt` exit successfully after overwriting config file
  cmd/commandfuncs.go
Labels: bug :lady_beetle:

#5350 cmd: Add `--envfile` flag to `validate` command
  cmd/commandfuncs.go
  cmd/commands.go
Labels: feature :gear:
