Repository caddyserver/caddy, pull requests merged in 2023-05, with the labels that each got.

#5500 acmeserver: Configurable `resolvers`, fix smallstep deprecations
  listeners.go
  listeners_test.go
  modules/caddyhttp/reverseproxy/upstreams.go
  modules/caddypki/acmeserver/acmeserver.go
  modules/caddypki/acmeserver/caddyfile.go
Labels: feature :gear:

#5515 fastcgi: Fix `capture_stderr`
  modules/caddyhttp/reverseproxy/fastcgi/fastcgi.go
Labels: bug :lady_beetle:

#5488 reverseproxy: Add `fallback` for some policies, instead of always random
  modules/caddyhttp/reverseproxy/selectionpolicies.go
  modules/caddyhttp/reverseproxy/selectionpolicies_test.go
Labels: feature :gear:

#5446 reverseproxy: Fix active health check header canonicalization, refactor
  modules/caddyhttp/reverseproxy/healthchecks.go
  modules/caddyhttp/reverseproxy/reverseproxy.go
Labels: bug :lady_beetle:

#5487 reverseproxy: Optimize the base case for `least_conn` policy
  modules/caddyhttp/reverseproxy/selectionpolicies.go
Labels: optimization :chart_with_downwards_trend:

#5521 feature: watch include directory
  cmd/main.go
Labels: feature :gear:

#5527 Initial implementation of fallback_sni
  caddyconfig/httpcaddyfile/httptype.go
  caddyconfig/httpcaddyfile/options.go
  go.mod
  go.sum
  modules/caddytls/connpolicy.go
Labels: feature :gear:

#5473 caddytls: Check for nil ALPN; close #5470
  modules/caddytls/connpolicy.go
Labels: bug :lady_beetle:

#5494 reverseproxy: Expand port ranges to multiple upstreams in CLI + Caddyfile
  caddytest/integration/caddyfile_adapt/reverse_proxy_port_range.txt
  modules/caddyhttp/reverseproxy/addresses.go
  modules/caddyhttp/reverseproxy/addresses_test.go
  modules/caddyhttp/reverseproxy/caddyfile.go
  modules/caddyhttp/reverseproxy/command.go
Labels: feature :gear:

#5535 headers: Add `>` Caddyfile shortcut for enabling `defer`
  caddytest/integration/caddyfile_adapt/header.txt
  modules/caddyhttp/headers/caddyfile.go
Labels: feature :gear:

#5107 caddyhttp: Implement named routes, `invoke` directive
  caddyconfig/caddyfile/parse.go
  caddyconfig/httpcaddyfile/builtins.go
  caddyconfig/httpcaddyfile/directives.go
  caddyconfig/httpcaddyfile/httptype.go
  caddytest/integration/caddyfile_adapt/invoke_named_routes.txt
  modules/caddyhttp/app.go
  modules/caddyhttp/invoke.go
  modules/caddyhttp/routes.go
  modules/caddyhttp/server.go
Labels: feature :gear:

#5547 fileserver: Allow Etag override
  modules/caddyhttp/fileserver/staticfiles.go
Labels: feature :gear:

#5539 Do not replace import tokens if they are part of a snippet
  caddyconfig/caddyfile/parse.go
  caddyconfig/httpcaddyfile/builtins_test.go
  caddyconfig/httpcaddyfile/testdata/import_variadic.txt
  caddyconfig/httpcaddyfile/testdata/import_variadic_snippet.txt
  caddyconfig/httpcaddyfile/testdata/import_variadic_with_import.txt
Labels: bug :lady_beetle:

#5553 templates: Add `readFile` function, skips parsing contents as a template
  modules/caddyhttp/templates/templates.go
  modules/caddyhttp/templates/tplcontext.go
Labels: feature :gear:

#5560 update quic-go to v0.35.0
  go.mod
  go.sum
  listeners.go
Labels: dependencies
