Repository caddyserver/caddy, pull requests merged in 2023-02, with the labels that each got.

#5353 chore: Build with Go 1.20, keep minimum at 1.18 for now
  .github/workflows/ci.yml
  .github/workflows/cross-build.yml
  .github/workflows/release.yml
  go.mod
  go.sum
  listeners.go
  modules/caddyhttp/app.go
  modules/caddyhttp/caddyhttp.go
  modules/caddyhttp/server.go
Labels: CI/CD :nut_and_bolt:

#5332 admin: Add `CADDY_ADMIN` env var to override the default
  admin.go
Labels: feature :gear:

#5344 caddyauth: Add singleflight for basic auth
  go.mod
  modules/caddyhttp/caddyauth/basicauth.go
Labels: bug :lady_beetle:

#5328 caddyhttp: Pluggable trusted proxy IP range sources
  caddyconfig/httpcaddyfile/serveroptions.go
  caddytest/integration/caddyfile_adapt/global_server_options_single.txt
  caddytest/integration/caddyfile_adapt/reverse_proxy_options.txt
  modules/caddyhttp/app.go
  modules/caddyhttp/ip_range.go
  modules/caddyhttp/server.go
Labels: feature :gear:

#5362 chore: Upgrade various dependencies
  go.mod
  go.sum
  modules/caddyhttp/app.go
  modules/caddyhttp/celmatcher.go
  modules/caddyhttp/fileserver/matcher.go
  modules/caddyhttp/fileserver/matcher_test.go
  modules/caddyhttp/templates/tplcontext.go
  modules/caddyhttp/tracing/tracer.go
Labels: feature :gear:

#5367 reverseproxy: Don't buffer chunked requests (fix #5366)
  modules/caddyhttp/reverseproxy/caddyfile.go
  modules/caddyhttp/reverseproxy/reverseproxy.go
Labels: bug :lady_beetle:

#5377 cmd: Adjust documentation for commands
  cmd/commands.go
  modules/caddyhttp/reverseproxy/command.go
Labels: documentation :books:

#5249 caddyfile: Implement variadics for import args placeholders
  caddyconfig/caddyfile/importargs.go
  caddyconfig/caddyfile/lexer.go
  caddyconfig/caddyfile/parse.go
  caddyconfig/caddyfile/parse_test.go
  caddyconfig/httpcaddyfile/builtins_test.go
Labels: feature :gear:

#5383 cmd: Fix validating JSON with unknown fields
  caddy.go
  cmd/commandfuncs.go
  context.go
  modules.go
Labels: bug :lady_beetle:

#5384 caddytls: Loosen the warning for on-demand
  modules/caddytls/tls.go
Labels: documentation :books:

#5369 reverseproxy: refactor HTTP transport layer
  caddytest/integration/reverseproxy_test.go
  modules/caddyhttp/reverseproxy/httptransport.go
Labels: under review :monocle_face:, optimization :chart_with_downwards_trend:

#5379 cmd: Expand cobra support, add short flags
  cmd/cobra.go
  cmd/commands.go
  modules/caddyhttp/caddyauth/command.go
  modules/caddyhttp/fileserver/command.go
  modules/caddyhttp/reverseproxy/command.go
  modules/caddyhttp/staticresp.go
  modules/caddypki/command.go
Labels: feature :gear:

#5385 caddyfile: Implement heredoc support
  caddyconfig/caddyfile/dispenser.go
  caddyconfig/caddyfile/lexer.go
  caddyconfig/caddyfile/lexer_test.go
  caddyconfig/caddyfile/testdata/import_args0.txt
  caddyconfig/caddyfile/testdata/import_args1.txt
  caddytest/integration/caddyfile_adapt/heredoc.txt
  caddytest/integration/caddyfile_adapt/import_args_snippet.txt
  caddytest/integration/caddyfile_adapt/reverse_proxy_options.txt
  caddytest/integration/testdata/import_respond.txt
  modules/caddyhttp/celmatcher.go
  modules/caddyhttp/reverseproxy/fastcgi/caddyfile.go
  modules/caddyhttp/reverseproxy/forwardauth/caddyfile.go
Labels: feature :gear:

#5404 caddyfile: Fix heredoc fuzz crasher, drop trailing newline
  caddyconfig/caddyfile/lexer.go
  caddyconfig/caddyfile/lexer_test.go
  caddytest/integration/caddyfile_adapt/heredoc.txt
Labels: bug :lady_beetle:

#5403 ci/cd: ship tarballs with vendored deps
  .goreleaser.yml
Labels: CI/CD :nut_and_bolt:
