Repository caddyserver/caddy, pull requests merged in 2023-08, with the labels that each got.

#5663 reverseproxy: Connection termination cleanup
  modules/caddyhttp/reverseproxy/reverseproxy.go
Labels: bug :lady_beetle:, under review :monocle_face:

#5664 core: Allow loopback hosts for admin endpoint (fix #5650)
  admin.go
  cmd/commandfuncs.go
Labels: bug :lady_beetle:, upstream :arrow_up:

#5654 caddyhttp: Make use of `http.ResponseController`
  caddyconfig/httpcaddyfile/serveroptions.go
  caddytest/integration/caddyfile_adapt/global_server_options_single.txt
  caddytest/integration/stream_test.go
  modules/caddyhttp/app.go
  modules/caddyhttp/duplex_go120.go
  modules/caddyhttp/duplex_go121.go
  modules/caddyhttp/encode/encode.go
  modules/caddyhttp/headers/headers.go
  modules/caddyhttp/push/handler.go
  modules/caddyhttp/responsewriter.go
  modules/caddyhttp/reverseproxy/reverseproxy.go
  modules/caddyhttp/reverseproxy/streaming.go
  modules/caddyhttp/reverseproxy/streaming_test.go
  modules/caddyhttp/server.go
Labels: feature :gear:

#5672 encode: Fix infinite recursion
  modules/caddyhttp/encode/encode.go
Labels: bug :lady_beetle:

#5679 reverseproxy: Fix hijack ordering which broke websockets
  modules/caddyhttp/reverseproxy/streaming.go
Labels: bug :lady_beetle:

#5691 chore: use `--clean` instead of `--rm-dist` for goreleaser
  .github/workflows/release.yml
Labels: CI/CD :nut_and_bolt:

#5685 import: check that matched key is not a substring of the replacement key
  caddyconfig/caddyfile/importargs.go
  caddyconfig/caddyfile/parse_test.go
Labels: bug :lady_beetle:

#5695 reverseproxy: do not parse upstream address too early if it contains replaceble parts
  caddytest/integration/caddyfile_adapt/replaceable_upstream.txt
  caddytest/integration/caddyfile_adapt/replaceable_upstream_partial_port.txt
  caddytest/integration/caddyfile_adapt/replaceable_upstream_port.txt
  modules/caddyhttp/reverseproxy/addresses.go
  modules/caddyhttp/reverseproxy/addresses_test.go
  modules/caddyhttp/reverseproxy/caddyfile.go
  modules/caddyhttp/reverseproxy/command.go
Labels: bug :lady_beetle:

#5696 cmd: fix cli when admin endpoint uses new unix socket permission format
  cmd/commandfuncs.go
  internal/sockets.go
  listeners.go
  listeners_test.go
Labels: bug :lady_beetle:

#5707 chore: use gofumpt
  .golangci.yml
  admin.go
  caddy.go
  caddyconfig/caddyfile/importgraph.go
  caddyconfig/caddyfile/parse.go
  caddyconfig/httpcaddyfile/addresses.go
  caddyconfig/httpcaddyfile/directives.go
  caddyconfig/httpcaddyfile/httptype.go
  caddyconfig/httpcaddyfile/pkiapp.go
  caddyconfig/httpcaddyfile/tlsapp.go
  caddytest/caddytest.go
  cmd/commandfuncs.go
  cmd/commands.go
  cmd/storagefuncs.go
  internal/sockets.go
  listeners.go
  modules/caddyhttp/caddyhttp.go
  modules/caddyhttp/celmatcher.go
  modules/caddyhttp/fileserver/browse.go
  modules/caddyhttp/matchers.go
  modules/caddyhttp/reverseproxy/addresses.go
  modules/caddyhttp/reverseproxy/caddyfile.go
  modules/caddyhttp/reverseproxy/command.go
  modules/caddyhttp/reverseproxy/fastcgi/client.go
  modules/caddyhttp/reverseproxy/reverseproxy.go
  modules/caddyhttp/reverseproxy/streaming.go
  modules/caddyhttp/templates/tplcontext.go
  modules/caddypki/acmeserver/acmeserver.go
  modules/caddypki/ca.go
  modules/caddytls/connpolicy.go
  modules/logging/filewriter.go
  modules/logging/filters.go
  replacer.go
Labels: CI/CD :nut_and_bolt:

#5720 feat: Add 64-bit RISC-V to goreleaser config
  .goreleaser.yml
Labels: CI/CD :nut_and_bolt:

#5614 cmd: Require config file exists for `caddy validate`
  cmd/commandfuncs.go
  cmd/main.go
Labels: bug :lady_beetle:

#5752 reverseproxy: Always return new upstreams (fix #5736)
  modules/caddyhttp/reverseproxy/reverseproxy.go
  modules/caddyhttp/reverseproxy/upstreams.go
Labels: bug :lady_beetle:

#5751 fileserver: docs: clarify the ability to produce JSON array with `browse`
  modules/caddyhttp/fileserver/staticfiles.go
Labels: documentation :books:

#5761 caddyfile: Loosen heredoc parsing
  caddyconfig/caddyfile/lexer.go
  caddyconfig/caddyfile/lexer_test.go
Labels: bug :lady_beetle:

#5757 httpcaddyfile: Stricter errors for site and upstream address schemes
  caddyconfig/httpcaddyfile/addresses.go
  caddytest/integration/caddyfile_test.go
  modules/caddyhttp/reverseproxy/caddyfile.go
Labels: feature :gear:

#5765 caddyfile: Adjust error formatting
  caddyconfig/caddyfile/dispenser.go
  caddyconfig/httpcaddyfile/builtins.go
Labels: feature :gear:

#5774 replacer: change timezone to UTC for "time.now.http" placeholders
  replacer.go
Labels: bug :lady_beetle:

#5769 caddyfile: Fix case where heredoc marker is empty after newline
  caddyconfig/caddyfile/lexer.go
  caddyconfig/caddyfile/lexer_test.go
Labels: bug :lady_beetle:

#5786 logging: Clone array on log filters, prevent side-effects
  modules/logging/filters.go
Labels: bug :lady_beetle:, needs tests :100:

#5779 logging: query filter for array of strings
  modules/logging/filters.go
  modules/logging/filters_test.go
Labels: feature :gear:
