Repository caddyserver/caddy, pull requests merged in 2024-06, with the labels that each got.

#6356 cmd: fix auto-detetction of .caddyfile extension
  cmd/main.go
Labels: bug :lady_beetle:

#6362 cmd: fix regression in auto-detect of Caddyfile
  cmd/main.go
  cmd/main_test.go
Labels: bug :lady_beetle:

#6370 cmd: remove zealous check of Caddyfile auto-detection
  cmd/main.go
  cmd/main_test.go
Labels: bug :lady_beetle:

#6376 ci: upgrade to goreleaser v2
  .github/workflows/ci.yml
  .github/workflows/release.yml
  .goreleaser.yml
Labels: CI/CD :nut_and_bolt:

#6378 Split `run` into a public `BuildContext` and a private part
  caddy.go
Labels: feature :gear:

#6391 logging: set file mode when the file already exist.
  modules/logging/filewriter.go
  modules/logging/filewriter_test.go
Labels: bug :lady_beetle:

#6130 caddyfile: Pass blocks to `import` for snippets
  caddyconfig/caddyfile/parse.go
  caddytest/integration/caddyfile_adapt/import_block_snippet.caddyfiletest
  caddytest/integration/caddyfile_adapt/import_block_snippet_args.caddyfiletest
  caddytest/integration/caddyfile_adapt/import_blocks_snippet.caddyfiletest
  caddytest/integration/caddyfile_adapt/import_blocks_snippet_nested.caddyfiletest
Labels: feature :gear:, discussion :speech_balloon:

#6398 reverseproxy: add Max-Age option to sticky cookie
  modules/caddyhttp/reverseproxy/selectionpolicies.go
Labels: feature :gear:
