Repository caddyserver/caddy, pull requests merged in 2024-09, with the labels that each got.

#6571 rewrite: Avoid panic on bad arg count for `uri`
  modules/caddyhttp/rewrite/caddyfile.go
Labels: bug :lady_beetle:

#6575 ci: update the linter action version
  .github/workflows/lint.yml
  .golangci.yml
  modules/caddyhttp/server.go
Labels: CI/CD :nut_and_bolt:

#6590 caddyhttp: Optimize logs using zap's WithLazy()
  modules/caddyhttp/server.go
Labels: optimization :chart_with_downwards_trend:

#6566 doc: remove docs of deprecated directives
  modules/caddytls/connpolicy.go
Labels: documentation :books:
