Repository caddyserver/caddy, pull requests merged in 2024-01, with the labels that each got.

#6010 caddyhttp: support unix sockets in `caddy respond` command
  modules/caddyhttp/staticresp.go
Labels: feature :gear:

#6011 chore: check against errors of `io/fs` instead of `os`
  caddy.go
  caddytest/caddytest.go
  cmd/commandfuncs.go
  cmd/main.go
  modules/caddyhttp/fileserver/browse.go
  modules/caddyhttp/fileserver/staticfiles.go
  modules/caddyhttp/templates/tplcontext_test.go
Labels: bug :lady_beetle:

#6021 Switch Solaris-derivatives away from listen_unix
  listen.go
  listen_unix.go
  listen_unix_setopt.go
Labels: bug :lady_beetle:

#5830 reverseproxy: only change the content-length header when the full request was buffered
  modules/caddyhttp/reverseproxy/reverseproxy.go
Labels: help wanted :sos:, under review :monocle_face:

#6025 tls: add reuse_private_keys
  caddyconfig/httpcaddyfile/builtins.go
  caddyconfig/httpcaddyfile/tlsapp.go
  modules/caddytls/automation.go
Labels: feature :gear:

#6022 httpcaddyfile: Support client auth verifiers
  caddyconfig/httpcaddyfile/builtins.go
Labels: feature :gear:

#6001 httpcaddyfile: Fix redir <to> html
  caddyconfig/httpcaddyfile/builtins.go
Labels: bug :lady_beetle:

#6031 ci/cd: use the build tag `nobadger` to exclude badgerdb
  .github/workflows/ci.yml
  .github/workflows/cross-build.yml
  .goreleaser.yml
  go.mod
  go.sum
Labels: CI/CD :nut_and_bolt:, dependencies :chains:

#5833 filesystem: Globally declared filesystems, `fs` directive
  caddy.go
  caddyconfig/caddyfile/dispenser_test.go
  caddyconfig/caddyfile/parse_test.go
  caddyconfig/httpcaddyfile/builtins.go
  caddyconfig/httpcaddyfile/directives.go
  caddyconfig/httpcaddyfile/directives_test.go
  caddyconfig/httpcaddyfile/httptype.go
  caddytest/integration/caddyfile_test.go
  caddytest/integration/reverseproxy_test.go
  caddytest/integration/sni_test.go
  caddytest/integration/stream_test.go
  context.go
  filesystem.go
  internal/filesystems/map.go
  internal/filesystems/os.go
  modules/caddyfs/filesystem.go
  modules/caddyhttp/encode/encode_test.go
  modules/caddyhttp/fileserver/browse.go
  modules/caddyhttp/fileserver/browsetplcontext.go
  modules/caddyhttp/fileserver/caddyfile.go
  modules/caddyhttp/fileserver/matcher.go
  modules/caddyhttp/fileserver/matcher_test.go
  modules/caddyhttp/fileserver/staticfiles.go
  modules/caddyhttp/matchers_test.go
  modules/caddyhttp/reverseproxy/ascii_test.go
  modules/caddyhttp/reverseproxy/fastcgi/client_test.go
  modules/caddyhttp/reverseproxy/selectionpolicies_test.go
  modules/caddyhttp/rewrite/rewrite_test.go
  modules/caddyhttp/tracing/tracerprovider_test.go
  modules/standard/imports.go
Labels: feature :gear:

#5995 replacer: Fix escaped closing braces
  caddytest/integration/caddyfile_adapt/uri_replace_brace_escape.txt
  caddytest/integration/caddyfile_test.go
  replacer.go
  replacer_test.go
Labels: bug :lady_beetle:

#5805 caddyhttp: Security enhancements for client IP parsing
  caddyconfig/httpcaddyfile/serveroptions.go
  modules/caddyhttp/server.go
  modules/caddyhttp/server_test.go
Labels: feature :gear:

#5851 reverseproxy: Add `tls_curves` option to HTTP transport
  modules/caddyhttp/reverseproxy/caddyfile.go
  modules/caddyhttp/reverseproxy/httptransport.go
Labels: feature :gear:

#5850 fileserver: Implement caddyfile.Unmarshaler interface
  modules/caddyhttp/fileserver/caddyfile.go
Labels: feature :gear:

#5844 httpcaddyfile: Rewrite `root` and `rewrite` parsing to allow omitting matcher
  caddyconfig/httpcaddyfile/builtins.go
  caddytest/integration/caddyfile_adapt/rewrite_directive_permutations.txt
  caddytest/integration/caddyfile_adapt/root_directive_permutations.txt
  modules/caddyhttp/rewrite/caddyfile.go
Labels: feature :gear:

#5965 httpcaddyfile: Add optional status code argument to `handle_errors` directive
  caddyconfig/httpcaddyfile/builtins.go
  caddyconfig/httpcaddyfile/httptype.go
  caddytest/integration/caddyfile_adapt/error_multi_site_blocks.txt
  caddytest/integration/caddyfile_adapt/error_range_codes.txt
  caddytest/integration/caddyfile_adapt/error_range_simple_codes.txt
  caddytest/integration/caddyfile_adapt/error_simple_codes.txt
  caddytest/integration/caddyfile_adapt/error_sort.txt
  caddytest/integration/caddyfile_test.go
Labels: feature :gear:

#6051 caddyfile: Allow heredoc blank lines
  caddyconfig/caddyfile/lexer.go
  caddyconfig/caddyfile/lexer_test.go
Labels: bug :lady_beetle:

#6056 caddyfile: Add heredoc support to `fmt` command
  caddyconfig/caddyfile/formatter.go
  caddyconfig/caddyfile/formatter_test.go
  caddyconfig/caddyfile/lexer.go
Labels: bug :lady_beetle:

#6054 matchers: `query` now ANDs multiple keys
  modules/caddyhttp/matchers.go
  modules/caddyhttp/matchers_test.go
Labels: bug :lady_beetle:

#6037 caddyfile: Normalize & flatten all unmarshalers
  caddyconfig/caddyfile/adapter.go
  caddyconfig/httpcaddyfile/builtins.go
  caddyconfig/httpcaddyfile/directives.go
  caddyconfig/httpcaddyfile/httptype.go
  caddyconfig/httpcaddyfile/options.go
  caddyconfig/httpcaddyfile/pkiapp.go
  caddyconfig/httpcaddyfile/serveroptions.go
  caddytest/integration/caddyfile_adapt/push.txt
  modules/caddyevents/eventsconfig/caddyfile.go
  modules/caddyhttp/caddyauth/caddyfile.go
  modules/caddyhttp/celmatcher.go
  modules/caddyhttp/encode/caddyfile.go
  modules/caddyhttp/encode/gzip/gzip.go
  modules/caddyhttp/fileserver/caddyfile.go
  modules/caddyhttp/fileserver/matcher.go
  modules/caddyhttp/headers/caddyfile.go
  modules/caddyhttp/ip_matchers.go
  modules/caddyhttp/map/caddyfile.go
  modules/caddyhttp/matchers.go
  modules/caddyhttp/proxyprotocol/module.go
  modules/caddyhttp/push/caddyfile.go
  modules/caddyhttp/requestbody/caddyfile.go
  modules/caddyhttp/responsematchers.go
  modules/caddyhttp/reverseproxy/caddyfile.go
  modules/caddyhttp/reverseproxy/fastcgi/caddyfile.go
  modules/caddyhttp/reverseproxy/selectionpolicies.go
  modules/caddyhttp/rewrite/caddyfile.go
  modules/caddyhttp/staticerror.go
  modules/caddyhttp/staticresp.go
  modules/caddyhttp/templates/caddyfile.go
  modules/caddyhttp/tracing/module.go
  modules/caddyhttp/vars.go
  modules/caddypki/acmeserver/caddyfile.go
  modules/caddytls/acmeissuer.go
  modules/caddytls/certmanagers.go
  modules/caddytls/internalissuer.go
  modules/caddytls/zerosslissuer.go
  modules/filestorage/filestorage.go
  modules/logging/encoders.go
  modules/logging/filewriter.go
  modules/logging/filterencoder.go
  modules/logging/filters.go
  modules/logging/netwriter.go
  modules/metrics/metrics.go
Labels: optimization :chart_with_downwards_trend:

#6040 caddyhttp: Fix panic when request missing ClientIPVarKey
  modules/caddyhttp/marshalers.go
Labels: bug :lady_beetle:

#5980 logging: Automatic `wrap` default for `filter` encoder
  caddytest/integration/caddyfile_adapt/log_filter_no_wrap.txt
  logging.go
  modules/logging/filterencoder.go
Labels: bug :lady_beetle:, feature :gear:

#6061 caddyfile: Switch to slices.Equal for better performance
  caddyconfig/caddyfile/formatter.go
Labels: optimization :chart_with_downwards_trend:

#6062 caddyfile: Correctly close the heredoc when the closing marker appears immediately
  caddyconfig/caddyfile/lexer.go
  caddyconfig/caddyfile/lexer_test.go
Labels: bug :lady_beetle:

#5961 chore: enabling a few more linters
  .github/workflows/lint.yml
  .golangci.yml
  caddyconfig/caddyfile/adapter.go
  caddytest/caddytest.go
  context.go
  logging.go
  modules/caddyhttp/encode/encode.go
  modules/caddyhttp/reverseproxy/fastcgi/client.go
  modules/caddyhttp/reverseproxy/httptransport.go
  modules/caddyhttp/reverseproxy/reverseproxy.go
  modules/caddytls/internalissuer.go
Labels: CI/CD :nut_and_bolt:

#5945 core: Add `ctx.Slogger()` which returns an `slog` logger
  context.go
  go.mod
  go.sum
Labels: feature :gear:
