Repository caddyserver/caddy, pull requests merged in 2024-12, with the labels that each got.

#6714 caddyhttp: Add `{?query}` placeholder
  caddyconfig/httpcaddyfile/shorthands.go
  caddytest/integration/caddyfile_adapt/php_fastcgi_expanded_form.caddyfiletest
  caddytest/integration/caddyfile_adapt/php_fastcgi_handle_response.caddyfiletest
  caddytest/integration/caddyfile_adapt/php_fastcgi_matcher.caddyfiletest
  caddytest/integration/caddyfile_adapt/php_fastcgi_subdirectives.caddyfiletest
  caddytest/integration/caddyfile_adapt/php_fastcgi_try_files_override.caddyfiletest
  modules/caddyhttp/replacer.go
  modules/caddyhttp/reverseproxy/fastcgi/caddyfile.go
Labels: bug :lady_beetle:, feature :gear:

#6699 fileserver: Add `first_exist_fallback` strategy for `try_files`
  caddytest/integration/caddyfile_adapt/php_fastcgi_handle_response.caddyfiletest
  caddytest/integration/caddyfile_adapt/php_fastcgi_matcher.caddyfiletest
  caddytest/integration/caddyfile_adapt/php_fastcgi_subdirectives.caddyfiletest
  caddytest/integration/caddyfile_adapt/php_fastcgi_try_files_override_no_dir_index.caddyfiletest
  modules/caddyhttp/fileserver/caddyfile.go
  modules/caddyhttp/fileserver/matcher.go
  modules/caddyhttp/reverseproxy/fastcgi/caddyfile.go
Labels: optimization :chart_with_downwards_trend:

#6727 fileserver: Fix policy `Validate()` oversight
  modules/caddyhttp/fileserver/matcher.go
Labels: bug :lady_beetle:

#6567 reverseproxy: Rewrite requests and responses for websocket over http2
  modules/caddyhttp/reverseproxy/reverseproxy.go
  modules/caddyhttp/reverseproxy/streaming.go
Labels: upstream :arrow_up:, go

#6629 caddyhttp: Allow matching Transfer-Encoding, add to access logs
  modules/caddyhttp/marshalers.go
  modules/caddyhttp/matchers.go
  modules/caddyhttp/responsematchers.go
Labels: bug :lady_beetle:

#6712 httpcaddyfile: Implement `force_automate`
  caddyconfig/httpcaddyfile/builtins.go
  caddyconfig/httpcaddyfile/httptype.go
  caddyconfig/httpcaddyfile/tlsapp.go
  caddytest/integration/caddyfile_adapt/tls_automation_wildcard_force_automate.caddyfiletest
  caddytest/integration/caddyfile_adapt/tls_automation_wildcard_shadowing.caddyfiletest
Labels: feature :gear:
