Repository caddyserver/caddy, pull requests merged in 2024-04, with the labels that each got.

#6093 caddyhttp: Added plaintext capability to `file_server browse`
  modules/caddyhttp/fileserver/browse.go
  modules/caddyhttp/fileserver/caddyfile.go
Labels: feature :gear:

#6221 chore: Upgrade some dependencies
  caddyconfig/caddyfile/formatter.go
  caddyconfig/httpcaddyfile/httptype.go
  go.mod
  go.sum
  modules/caddyhttp/matchers.go
Labels: dependencies :chains:

#6223 chore: Fix broken links in README.md
  README.md
Labels: documentation :books:

#6225 gitignore: Add rule for caddyfile.go
  .gitignore
Labels: bug :lady_beetle:

#6208 admin: Making `Etag` a header, not a trailer
  admin.go
Labels: bug :lady_beetle:

#5919 Added special case support for caddyfile suffix, case insensitive
  cmd/main.go
Labels: under review :monocle_face:

#6065 reverseproxy: Implement modular CA provider for TLS transport
  caddytest/integration/caddyfile_adapt/reverse_proxy_http_transport_tls_file_cert.txt
  caddytest/integration/caddyfile_adapt/reverse_proxy_http_transport_tls_inline_cert.txt
  modules/caddyhttp/reverseproxy/caddyfile.go
  modules/caddyhttp/reverseproxy/httptransport.go
  modules/caddyhttp/reverseproxy/httptransport_test.go
Labels: feature :gear:

#6222 fileserver: Read Etags from precomputed files
  caddytest/integration/caddyfile_adapt/file_server_etag_file_extensions.caddyfiletest
  modules/caddyhttp/fileserver/caddyfile.go
  modules/caddyhttp/fileserver/staticfiles.go
Labels: feature :gear:

#6229 Upgrade: ACMEz v2, CertMagic, and ZeroSSL issuer
  admin.go
  caddyconfig/httpcaddyfile/builtins.go
  caddyconfig/httpcaddyfile/options.go
  caddyconfig/httpcaddyfile/tlsapp.go
  caddytest/integration/acme_test.go
  caddytest/integration/acmeserver_test.go
  caddytest/integration/caddyfile_adapt/global_options_preferred_chains.caddyfiletest
  caddytest/integration/caddyfile_adapt/tls_automation_policies_3.caddyfiletest
  caddytest/integration/caddyfile_adapt/tls_automation_policies_4.caddyfiletest
  caddytest/integration/caddyfile_adapt/tls_automation_policies_8.caddyfiletest
  caddytest/integration/caddyfile_adapt/tls_automation_policies_global_email_localhost.caddyfiletest
  caddytest/integration/caddyfile_adapt/tls_dns_ttl.caddyfiletest
  caddytest/integration/caddyfile_adapt/tls_explicit_issuer_dns_ttl.caddyfiletest
  caddytest/integration/caddyfile_adapt/tls_explicit_issuer_propagation_options.caddyfiletest
  caddytest/integration/caddyfile_adapt/tls_propagation_options.caddyfiletest
  cmd/caddy/setcap.sh
  go.mod
  go.sum
  modules/caddyhttp/autohttps.go
  modules/caddyhttp/reverseproxy/fastcgi/client_test.go
  modules/caddytls/acmeissuer.go
  modules/caddytls/automation.go
  modules/caddytls/capools.go
  modules/caddytls/certmanagers.go
  modules/caddytls/connpolicy.go
  modules/caddytls/tls.go
  modules/caddytls/zerosslissuer.go
Labels: feature :gear:, dependencies :chains:

#6175 reverseproxy: Wait for both ends of websocket connections to close
  modules/caddyhttp/reverseproxy/reverseproxy.go
  modules/caddyhttp/reverseproxy/streaming.go
Labels: bug :lady_beetle:

#6074 connection policy: add `local_ip` matcher
  modules/caddytls/matchers.go
  modules/caddytls/matchers_test.go
Labels: feature :gear:, discussion :speech_balloon:

#6140 encode: Add `zstd` compression level support
  modules/caddyhttp/encode/zstd/zstd.go
Labels: feature :gear:

#6088 caddyhttp: Support multiple logger names per host
  caddyconfig/httpcaddyfile/httptype.go
  caddytest/integration/caddyfile_adapt/import_args_snippet.caddyfiletest
  caddytest/integration/caddyfile_adapt/log_except_catchall_blocks.caddyfiletest
  caddytest/integration/caddyfile_adapt/log_multi_logger_name.caddyfiletest
  caddytest/integration/caddyfile_adapt/log_override_hostname.caddyfiletest
  caddytest/integration/caddyfile_adapt/log_override_name_multiaccess.caddyfiletest
  caddytest/integration/caddyfile_adapt/log_override_name_multiaccess_debug.caddyfiletest
  caddytest/integration/caddyfile_adapt/log_skip_hosts.caddyfiletest
  modules/caddyhttp/logging.go
  modules/caddyhttp/server.go
Labels: feature :gear:

#6145 caddyfile: Populate regexp matcher names by default
  caddyconfig/caddyfile/dispenser.go
  caddyconfig/httpcaddyfile/httptype.go
  caddyconfig/httpcaddyfile/serveroptions.go
  caddyconfig/httpcaddyfile/tlsapp.go
  caddytest/integration/caddyfile_adapt/expression_quotes.caddyfiletest
  caddytest/integration/caddyfile_adapt/matcher_syntax.caddyfiletest
  caddytest/integration/caddyfile_adapt/shorthand_parameterized_placeholders.caddyfiletest
  context.go
  modules/caddyhttp/celmatcher.go
  modules/caddyhttp/celmatcher_test.go
  modules/caddyhttp/fileserver/matcher_test.go
  modules/caddyhttp/matchers.go
  modules/caddyhttp/routes.go
  modules/caddyhttp/vars.go
Labels: feature :gear:, under review :monocle_face:

#6249 staticresp: Use the evaluated response body for sniffing JSON content-type
  caddytest/integration/handler_test.go
  modules/caddyhttp/staticresp.go
Labels: bug :lady_beetle:

#6250 cmd: Only validate config is proper JSON if config slice has data
  .github/workflows/ci.yml
  cmd/main.go
Labels: bug :lady_beetle:

#6251 logging: Fix default access logger
  modules/caddyhttp/app.go
  modules/caddyhttp/logging.go
  modules/caddyhttp/server.go
Labels: bug :lady_beetle:

#6263 doc: add `verifier` in `ClientAuthentication` caddyfile marshaler doc
  modules/caddytls/connpolicy.go
Labels: documentation :books:

#6252 caddyhttp: Address some Go 1.20 features
  cmd/x509rootsfallback.go
  go.mod
  go.sum
  modules/caddyhttp/caddyhttp.go
  modules/caddyhttp/caddyhttp_test.go
  modules/caddyhttp/requestbody/caddyfile.go
  modules/caddyhttp/requestbody/requestbody.go
  modules/caddyhttp/responsewriter_test.go
Labels: feature :gear:

#5463 replacer: Implement `file.*` global replacements
  caddytest/integration/testdata/foo.txt
  modules/caddyhttp/templates/tplcontext.go
  replacer.go
  replacer_test.go
Labels: feature :gear:

#6253 caddytls: Add option to configure certificate lifetime
  caddyconfig/httpcaddyfile/options.go
  caddyconfig/httpcaddyfile/tlsapp.go
  go.mod
  go.sum
  modules/caddytls/acmeissuer.go
Labels: feature :gear:

#6268 ci: remove `android` and `plan9` from cross-build workflow
  .github/workflows/cross-build.yml
Labels: CI/CD :nut_and_bolt:

#6274 reverse_proxy: handle buffered data during hijack
  modules/caddyhttp/responsewriter.go
  modules/caddyhttp/reverseproxy/streaming.go
Labels: bug :lady_beetle:

#6266 caddytls: Evict internal certs from cache based on issuer
  go.mod
  go.sum
  modules/caddytls/tls.go
Labels: bug :lady_beetle:
