Repository caddyserver/caddy, pull requests merged in 2024-02, with the labels that each got.

#5973 fileserver: Browse symlink display shows the target
  modules/caddyhttp/fileserver/browse.go
  modules/caddyhttp/fileserver/browse.html
  modules/caddyhttp/fileserver/browsetplcontext.go
  modules/caddyhttp/fileserver/caddyfile.go
  modules/caddyhttp/fileserver/command.go
Labels: feature :gear:

#6085 matchers: Drop `forwarded` option from `remote_ip` matcher
  modules/caddyhttp/celmatcher_test.go
  modules/caddyhttp/ip_matchers.go
Labels: bug :lady_beetle:

#6081 encode: Compress more media types by default
  modules/caddyhttp/encode/encode.go
Labels: bug :lady_beetle:

#6089 chore: Rename CI jobs, run on M1 mac
  .github/workflows/ci.yml
  .github/workflows/cross-build.yml
  .github/workflows/lint.yml
Labels: CI/CD :nut_and_bolt:

#6098 caddyfile: Reject long heredoc markers
  caddyconfig/caddyfile/formatter.go
  caddyconfig/caddyfile/formatter_test.go
  caddyconfig/caddyfile/lexer.go
  caddyconfig/caddyfile/testdata/clusterfuzz-testcase-minimized-fuzz-format-5806400649363456
Labels: bug :lady_beetle:, CI/CD :nut_and_bolt:

#6094 logging: Inline Caddyfile syntax for `ip_mask` filter
  caddytest/integration/caddyfile_adapt/log_filters.txt
  modules/logging/filters.go
Labels: feature :gear:

#6092 caddyauth: Rename `basicauth` to `basic_auth`
  caddyconfig/caddyfile/parse_test.go
  caddyconfig/httpcaddyfile/directives.go
  modules/caddyhttp/caddyauth/caddyfile.go
Labels: feature :gear:

#6091 caddyauth: Drop support for `scrypt`
  modules/caddyhttp/caddyauth/basicauth.go
  modules/caddyhttp/caddyauth/caddyfile.go
  modules/caddyhttp/caddyauth/command.go
  modules/caddyhttp/caddyauth/hashes.go
Labels: feature :gear:

#6102 caddyhttp: Only attempt to enable full duplex for HTTP/1.x
  modules/caddyhttp/server.go
Labels: bug :lady_beetle:

#5948 caddyhttp: Register post-shutdown callbacks
  modules/caddyhttp/app.go
  modules/caddyhttp/server.go
Labels: feature :gear:

#6104 caddyfile: Reject directives in the place of site addresses
  caddyconfig/caddyfile/parse.go
  caddyconfig/caddyfile/parse_test.go
  caddyconfig/httpcaddyfile/addresses.go
  caddyconfig/httpcaddyfile/httptype.go
  caddytest/integration/acme_test.go
  caddytest/integration/caddyfile_adapt/http_valid_directive_like_site_address.txt
  caddytest/integration/caddyfile_test.go
  caddytest/integration/pki_test.go
Labels: bug :lady_beetle:

#6118 chore: Update Chroma to get the new Caddyfile lexer
  go.mod
  go.sum
Labels: feature :gear:, upstream :arrow_up:

#6117 caddyfile: Assert having a space after heredoc marker to simply check
  caddyconfig/caddyfile/formatter.go
Labels: bug :lady_beetle:

#6103 tests: uses testing.TB interface
  caddytest/caddytest.go
Labels: CI/CD :nut_and_bolt:

#5796 acmeserver: add policy field to define allow/deny rules
  caddytest/integration/acme_test.go
  caddytest/integration/acmeserver_test.go
  modules/caddypki/acmeserver/acmeserver.go
  modules/caddypki/acmeserver/caddyfile.go
  modules/caddypki/acmeserver/policy.go
  modules/caddypki/acmeserver/policy_test.go
Labels: feature :gear:

#6127 caddytls: verifier: caddyfile: re-add Caddyfile support
  caddytest/integration/caddyfile_adapt/tls_client_auth_cert_file-legacy-with-verifier.caddyfiletest
  caddytest/integration/caddyfile_adapt_test.go
  internal/testmocks/dummyverifier.go
  modules/caddytls/connpolicy.go
Labels: bug :lady_beetle:
