Repository caddyserver/caddy, pull requests merged in 2024-03, with the labels that each got.

#5832 reverseproxy: SRV dynamic upstream failover
  modules/caddyhttp/reverseproxy/upstreams.go
Labels: feature :gear:

#6032 cmd: Adjust config load logs/errors
  cmd/main.go
Labels: bug :lady_beetle:

#6050 caddytls: clientauth: leaf verifier: make trusted leaf certs source pluggable
  caddytest/integration/leafcertloaders_test.go
  caddytest/leafcert.pem
  go.mod
  go.sum
  modules/caddytls/connpolicy.go
  modules/caddytls/leaffileloader.go
  modules/caddytls/leaffileloader_test.go
  modules/caddytls/leaffolderloader.go
  modules/caddytls/leaffolderloader_test.go
  modules/caddytls/leafpemloader.go
  modules/caddytls/leafpemloader_test.go
  modules/caddytls/leafstorageloader.go
Labels: feature :gear:

#6108 vars: Allow overriding `http.auth.user.id` in replacer as a special case
  modules/caddyhttp/vars.go
Labels: feature :gear:

#6149 ci: fix the integration test `TestLeafCertLoaders`
  caddytest/integration/leafcertloaders_test.go
Labels: CI/CD :nut_and_bolt:

#6069 logging: Implement `append` encoder, allow flatter filters config
  .github/workflows/ci.yml
  .github/workflows/cross-build.yml
  .github/workflows/lint.yml
  caddytest/integration/caddyfile_adapt/log_append_encoder.caddyfiletest
  caddytest/integration/caddyfile_adapt/log_filters.caddyfiletest
  modules/logging/appendencoder.go
  modules/logging/filterencoder.go
Labels: feature :gear:

#6113 httpcaddyfile: Allow nameless regexp placeholder shorthand
  caddyconfig/httpcaddyfile/shorthands.go
  caddytest/integration/caddyfile_adapt/shorthand_parameterized_placeholders.caddyfiletest
Labels: bug :lady_beetle:

#6066 logging: Implement `log_append` handler
  caddyconfig/httpcaddyfile/builtins.go
  caddyconfig/httpcaddyfile/directives.go
  caddytest/integration/caddyfile_adapt/log_add.caddyfiletest
  caddytest/integration/caddyfile_adapt/log_except_catchall_blocks.caddyfiletest
  modules/caddyhttp/logging.go
  modules/caddyhttp/logging/caddyfile.go
  modules/caddyhttp/logging/logadd.go
  modules/caddyhttp/server.go
  modules/caddyhttp/standard/imports.go
Labels: feature :gear:

#6109 fileserver: Preserve query during canonicalization redirect
  modules/caddyhttp/fileserver/staticfiles.go
Labels: bug :lady_beetle:

#6120 rewrite: Implement `uri query` operations
  caddytest/integration/caddyfile_test.go
  modules/caddyhttp/rewrite/caddyfile.go
  modules/caddyhttp/rewrite/rewrite.go
Labels: feature :gear:

#5865 httpcaddyfile: Add `RegisterDirectiveOrder` function for plugin authors
  caddyconfig/httpcaddyfile/directives.go
  caddyconfig/httpcaddyfile/options.go
Labels: feature :gear:

#6153 httpcaddyfile: Keep deprecated `skip_log` in directive order
  caddyconfig/httpcaddyfile/directives.go
Labels: bug :lady_beetle:

#6164 encode: write status immediately when status code is informational
  modules/caddyhttp/encode/encode.go
Labels: bug :lady_beetle:

#6168 chore: encode: use FlushError instead of Flush
  modules/caddyhttp/encode/encode.go
Labels: bug :lady_beetle:

#6150 http: suppress flushing if the response is being buffered
  modules/caddyhttp/responsewriter.go
Labels: bug :lady_beetle:

#6169 chore: Bump Chroma to v2.13.0, includes new Caddyfile lexer
  go.mod
  go.sum
Labels: dependencies :chains:

#6114 reverseproxy: Configurable forward proxy URL
  modules/caddyhttp/reverseproxy/caddyfile.go
  modules/caddyhttp/reverseproxy/httptransport.go
Labels: feature :gear:, under review :monocle_face:

#6154 reverseproxy: active health check allows configurable health_passes and health_fails
  caddytest/integration/reverseproxy_test.go
  modules/caddyhttp/reverseproxy/caddyfile.go
  modules/caddyhttp/reverseproxy/healthchecks.go
  modules/caddyhttp/reverseproxy/hosts.go
Labels: under review :monocle_face:

#6183 caddyhttp: Accept XFF header values with ports, when parsing client IP
  modules/caddyhttp/server.go
  modules/caddyhttp/server_test.go
Labels: bug :lady_beetle:

#6176 chore: Update quic-go to v0.42.0
  go.mod
  go.sum
  listeners.go
  modules/caddyhttp/server.go
Labels: upstream :arrow_up:

#6174 vars: Make nil values act as empty string instead of `"<nil>"`
  modules/caddyhttp/vars.go
Labels: bug :lady_beetle:

#6163 caddyhttp: Allow `header` replacement with empty string
  modules/caddyhttp/headers/caddyfile.go
  modules/caddyhttp/push/caddyfile.go
  modules/caddyhttp/reverseproxy/caddyfile.go
Labels: bug :lady_beetle:

#6184 replacer: use RWMutex to protect static provider
  replacer.go
  replacer_test.go
Labels: bug :lady_beetle:, under review :monocle_face:

#6187 logging: support `ms` duration format and add docs
  modules/logging/encoders.go
Labels: feature :gear:, under review :monocle_face:

#6165 rewrite: `uri query` replace operation
  caddytest/integration/caddyfile_adapt/uri_query_operations.caddyfiletest
  caddytest/integration/caddyfile_test.go
  modules/caddyhttp/rewrite/caddyfile.go
  modules/caddyhttp/rewrite/rewrite.go
Labels: feature :gear:

#6191 Added a null check to avoid segfault in rewrite module provision
  modules/caddyhttp/rewrite/rewrite.go
Labels: bug :lady_beetle:

#6198 chore: upgrade deps
  go.mod
  go.sum
Labels: under review :monocle_face:, dependencies :chains:

#6203 Added Faster Non-cryptographic Hash Function for Load Balancing
  modules/caddyhttp/reverseproxy/selectionpolicies.go
  modules/caddyhttp/reverseproxy/selectionpolicies_test.go
Labels: under review :monocle_face:
