Repository caddyserver/caddy, pull requests merged in 2024-10, with the labels that each got.

#6599 caddyhttp: Fix listener wrapper regression from #6573
  listeners.go
  modules/caddyhttp/app.go
Labels: bug :lady_beetle:

#6598 chore: Adjust incorrect `reverse_proxy` Caddyfile comment
  modules/caddyhttp/reverseproxy/caddyfile.go
Labels: documentation :books:

#6565 http: ReponseWriter prefer ReadFrom if available
  modules/caddyhttp/responsewriter.go
Labels: bug :lady_beetle:

#6369 caddytls: Support new tls.context module
  modules/caddytls/connpolicy.go
Labels: feature :gear:

#6594 caddyhttp: Escaping placeholders in CEL, add `vars` and `vars_regexp`
  .github/workflows/ci.yml
  .golangci.yml
  go.mod
  go.sum
  modules/caddyhttp/celmatcher.go
  modules/caddyhttp/celmatcher_test.go
  modules/caddyhttp/fileserver/matcher.go
  modules/caddyhttp/matchers.go
  modules/caddyhttp/templates/templates.go
  modules/caddyhttp/templates/tplcontext.go
  modules/caddyhttp/vars.go
Labels: feature :gear:

#6146 autohttps: Implement `auto_https prefer_wildcard` option
  caddyconfig/httpcaddyfile/httptype.go
  caddyconfig/httpcaddyfile/options.go
  caddyconfig/httpcaddyfile/tlsapp.go
  caddytest/integration/caddyfile_adapt/auto_https_prefer_wildcard.caddyfiletest
  caddytest/integration/caddyfile_adapt/wildcard_pattern.caddyfiletest
  caddytest/integration/mockdns_test.go
  modules/caddyhttp/autohttps.go
Labels: feature :gear:

#6602 ci: install xcaddy to fix release flow
  .github/workflows/ci.yml
  .github/workflows/release.yml
  .goreleaser.yml
  cmd/commands.go
Labels: CI/CD :nut_and_bolt:

#6620 docs: expand proxy protocol docs
  modules/caddyhttp/proxyprotocol/listenerwrapper.go
Labels: documentation :books:

#6616 caddyfile: Fix comma edgecase in address parsing
  caddyconfig/caddyfile/parse.go
  caddyconfig/caddyfile/parse_test.go
Labels: bug :lady_beetle:

#6621 reverseproxy: Use correct cases for websocket related headers
  modules/caddyhttp/reverseproxy/reverseproxy.go
  modules/caddyhttp/reverseproxy/streaming.go
Labels: bug :lady_beetle:

#6213 caddyhttp: Close http3 server gracefully
  modules/caddyhttp/app.go
  modules/caddyhttp/server.go
Labels: upstream :arrow_up:

#6624 fileserver: fix try_policy when instantiating file matcher from CEL
  modules/caddyhttp/fileserver/matcher.go
  modules/caddyhttp/fileserver/matcher_test.go
  modules/caddyhttp/fileserver/testdata/large.txt
Labels: bug :lady_beetle:

#6646 tracing: Add `spanID` field to access logs and `http.vars.span_id` placeholder
  modules/caddyhttp/server_test.go
  modules/caddyhttp/tracing/tracer.go
Labels: feature :gear:

#6656 reverseproxy: Sync changes from stdlib for 1xx handling
  modules/caddyhttp/headers/headers.go
  modules/caddyhttp/reverseproxy/reverseproxy.go
Labels: go

#6636 httpcaddyfile: Fixes for `prefer_wildcard` mode
  caddyconfig/httpcaddyfile/httptype.go
  caddyconfig/httpcaddyfile/tlsapp.go
  caddytest/integration/caddyfile_adapt/auto_https_prefer_wildcard.caddyfiletest
  caddytest/integration/caddyfile_adapt/auto_https_prefer_wildcard_multi.caddyfiletest
Labels: bug :lady_beetle:
