Repository caddyserver/caddy, pull requests merged in 2024-08, with the labels that each got.

#6411 replacer: `{file.*}` global placeholder strips trailing newline
  caddytest/integration/testdata/foo_with_multiple_trailing_newlines.txt
  caddytest/integration/testdata/foo_with_trailing_newline.txt
  replacer.go
  replacer_test.go
Labels: bug :lady_beetle:

#6500 go.mod: update update golang/x/net
  go.mod
  go.sum
Labels: bug :lady_beetle:

#6519 ci: don't exit early on error in remote CI machine
  .github/workflows/ci.yml
Labels: CI/CD :nut_and_bolt:

#6520 reverseproxy: Active health checks request body option
  caddytest/integration/caddyfile_adapt/reverse_proxy_health_reqbody.caddyfiletest
  modules/caddyhttp/reverseproxy/caddyfile.go
  modules/caddyhttp/reverseproxy/healthchecks.go
Labels: feature :gear:

#6536 error: run `error` (msg) through replacer
  caddytest/caddytest_test.go
  modules/caddyhttp/staticerror.go
Labels: feature :gear:

#6504 reverseproxy: allow user to define source address
  caddytest/integration/caddyfile_adapt/reverse_proxy_localaddr.caddyfiletest
  modules/caddyhttp/reverseproxy/caddyfile.go
  modules/caddyhttp/reverseproxy/httptransport.go
Labels: feature :gear:

#6406 ci: prepare syso files for windows embedding in release
  .goreleaser.yml
Labels: feature :gear:
