Repository caddyserver/caddy, pull requests merged in 2024-07, with the labels that each got.

#6419 reverseproxy: Only log host is up status on change
  modules/caddyhttp/reverseproxy/healthchecks.go
Labels: bug :lady_beetle:

#6440 reverseproxy: Add placeholder for host in active health check headers
  modules/caddyhttp/reverseproxy/healthchecks.go
Labels: feature :gear:

#6412 fileserver: Exclude symlink target size from total, show arrow on size
  .github/workflows/ci.yml
  modules/caddyhttp/fileserver/browse.html
  modules/caddyhttp/fileserver/browsetplcontext.go
Labels: bug :lady_beetle:

#6450 reverseproxy: Add placeholder for networkAddr in active health check headers
  modules/caddyhttp/reverseproxy/healthchecks.go
Labels: feature :gear:

#6454 reverseproxy: Caddyfile support for health_method
  caddytest/integration/caddyfile_adapt/reverse_proxy_health_method.caddyfiletest
  modules/caddyhttp/reverseproxy/caddyfile.go
Labels: feature :gear:

#6451 reverseproxy: add health_upstream subdirective
  modules/caddyhttp/reverseproxy/caddyfile.go
  modules/caddyhttp/reverseproxy/healthchecks.go
  modules/caddyhttp/reverseproxy/hosts.go
Labels: feature :gear:

#6470 ci: correct `-tags nobadger` on binary build
  .github/workflows/ci.yml
Labels: CI/CD :nut_and_bolt:

#6479 chore: update golangci config
  .golangci.yml
Labels: CI/CD :nut_and_bolt:
