Repository caddyserver/caddy, pull requests merged in 2024-05, with the labels that each got.

#6288 httpcaddyfile: Fix expression matcher shortcut in snippets
  caddyconfig/caddyfile/lexer.go
  caddyconfig/httpcaddyfile/httptype.go
  caddytest/integration/caddyfile_adapt/expression_quotes.caddyfiletest
Labels: bug :lady_beetle:

#6301 transport: fix proxy protocol initialization
  modules/caddyhttp/reverseproxy/httptransport.go
Labels: bug :lady_beetle:

#6302 reverseproxy: Stop following redirects in health checks by default, add `health_follow_redirects`
  modules/caddyhttp/reverseproxy/caddyfile.go
  modules/caddyhttp/reverseproxy/healthchecks.go
Labels: feature :gear:

#6308 tracing: add `http.vars.trace_id` placeholder
  modules/caddyhttp/tracing/tracer.go
Labels: feature :gear:

#6307 reverseproxy: use pointer when loading modules and remove LazyCertPool
  modules/caddyhttp/reverseproxy/httptransport.go
  modules/caddytls/capools.go
  modules/caddytls/capools_test.go
Labels: bug :lady_beetle:

#6310 chore: Bump Go version in CI
  .github/workflows/ci.yml
  .github/workflows/cross-build.yml
  .github/workflows/lint.yml
  .github/workflows/release.yml
Labels: CI/CD :nut_and_bolt:

#6082 logging: Add support for additional logger filters other than hostname
  caddyconfig/httpcaddyfile/builtins.go
  caddyconfig/httpcaddyfile/directives.go
  caddyconfig/httpcaddyfile/httptype.go
  caddytest/integration/caddyfile_adapt/log_filter_with_header.txt
  modules/caddyhttp/logging.go
  modules/caddyhttp/server.go
Labels: feature :gear:

#6232 feat: add generic response interceptors
  caddyconfig/httpcaddyfile/directives.go
  caddyconfig/httpcaddyfile/shorthands.go
  caddytest/integration/caddyfile_adapt/intercept_response.caddyfiletest
  caddytest/integration/intercept_test.go
  modules/caddyhttp/intercept/intercept.go
  modules/caddyhttp/standard/imports.go
Labels: feature :gear:

#6316 caddytest: normalize the JSON config
  caddytest/caddytest.go
  caddytest/caddytest_test.go
Labels: CI/CD :nut_and_bolt:

#6324 caddytls: set SNI server name in context
  go.mod
  go.sum
  modules/caddytls/certmanagers.go
Labels: feature :gear:

#6278 templates: Add `pathEscape` template function and use it in `browse.html`
  modules/caddyhttp/fileserver/browse.html
  modules/caddyhttp/templates/templates.go
  modules/caddyhttp/templates/tplcontext.go
Labels: feature :gear:

#6313 caddyhttp: Trace individual middleware handlers
  caddyconfig/httpcaddyfile/serveroptions.go
  modules/caddyhttp/app.go
  modules/caddyhttp/logging.go
  modules/caddyhttp/routes.go
  modules/caddyhttp/server.go
Labels: feature :gear:

#6326 caddytls: remove ClientHelloSNICtxKey
  modules/caddytls/certmanagers.go
Labels: feature :gear:

#6328 caddytls: fix permission requirement with AutomationPolicy
  modules/caddytls/automation.go
Labels: bug :lady_beetle:

#6292 context: AppIfConfigured returns error; consider not-yet-provisioned modules
  context.go
  modules/caddypki/adminapi.go
  modules/caddytls/capools.go
  modules/caddytls/tls.go
Labels: feature :gear:

#6312 reverseproxy: Support HTTP/3 transport to backend
  modules/caddyhttp/reverseproxy/httptransport.go
Labels: feature :gear:

#6185 autohttps: Move log WARN to INFO, reduce confusion
  modules/caddyhttp/autohttps.go
Labels: bug :lady_beetle:

#6339 caddyfile: Reject global request matchers earlier
  caddyconfig/caddyfile/parse.go
  caddyconfig/caddyfile/parse_test.go
Labels: bug :lady_beetle:

#6345 acmeserver: Add `sign_with_root` for Caddyfile
  caddytest/integration/caddyfile_adapt/acme_server_sign_with_root.caddyfiletest
  modules/caddypki/acmeserver/caddyfile.go
Labels: feature :gear:

#6350 caddyhttp: Fix merging consecutive `client_ip` or `remote_ip` matchers
  caddytest/integration/caddyfile_adapt/matcher_syntax.caddyfiletest
  modules/caddyhttp/ip_matchers.go
Labels: bug :lady_beetle:
