Repository caddyserver/caddy, pull requests merged in 2024-11, with the labels that each got.

#6608 forwardauth: Skip copying missing response headers
  caddytest/integration/caddyfile_adapt/forward_auth_authelia.caddyfiletest
  caddytest/integration/caddyfile_adapt/forward_auth_rename_headers.caddyfiletest
  modules/caddyhttp/reverseproxy/forwardauth/caddyfile.go
Labels: bug :lady_beetle:

#6596 caddyhttp: Add `MatchWithError` to replace SetVar hack
  caddyconfig/httpcaddyfile/httptype.go
  modules/caddyhttp/caddyhttp.go
  modules/caddyhttp/celmatcher.go
  modules/caddyhttp/celmatcher_test.go
  modules/caddyhttp/fileserver/matcher.go
  modules/caddyhttp/fileserver/matcher_test.go
  modules/caddyhttp/ip_matchers.go
  modules/caddyhttp/matchers.go
  modules/caddyhttp/matchers_test.go
  modules/caddyhttp/reverseproxy/healthchecks.go
  modules/caddyhttp/reverseproxy/httptransport.go
  modules/caddyhttp/reverseproxy/reverseproxy.go
  modules/caddyhttp/routes.go
  modules/caddyhttp/vars.go
  modules/caddytls/connpolicy.go
  modules/caddytls/ondemand.go
Labels: feature :gear:

#6676 go.mod: upgrade only some otel deps
  go.mod
  go.sum
Labels: CI/CD :nut_and_bolt:

#6648 fileserver: Add `file_limit` option for browse
  caddytest/integration/caddyfile_adapt/file_server_file_limit.caddyfiletest
  modules/caddyhttp/fileserver/browse.go
  modules/caddyhttp/fileserver/caddyfile.go
  modules/caddyhttp/fileserver/command.go
Labels: feature :gear:

#6662 rewrite: Don't add `/` in Caddyfile, do it after replacer
  modules/caddyhttp/rewrite/caddyfile.go
  modules/caddyhttp/rewrite/rewrite.go
  modules/caddyhttp/rewrite/rewrite_test.go
Labels: bug :lady_beetle:

#6593 caddytls: Allow disabling storage cleaning, avoids writing two files
  caddyconfig/httpcaddyfile/options.go
  caddyconfig/httpcaddyfile/tlsapp.go
  caddytest/integration/caddyfile_adapt/global_options.caddyfiletest
  modules/caddytls/tls.go
Labels: feature :gear:

#6677 ci: use commit sha in goreleaser-check
  .github/workflows/ci.yml
Labels: CI/CD :nut_and_bolt:

#6681 reverseproxy: Allow `0` as weights for `weighted_round_robin`
  modules/caddyhttp/reverseproxy/selectionpolicies.go
  modules/caddyhttp/reverseproxy/selectionpolicies_test.go
Labels: bug :lady_beetle:

#6691 chore: Add `provides` to `.deb` releases
  .goreleaser.yml
Labels: CI/CD :nut_and_bolt:

#6692 chore: make FastAbs comment easier to understand
  filepath.go
  filepath_windows.go
Labels: documentation :books:

#6720 ci: prevent jobs running on PRs from forks
  .github/workflows/ci.yml
Labels: CI/CD :nut_and_bolt:
