Repository caddyserver/caddy, pull requests merged in 2025-01, with the labels that each got.

#6759 reverse proxy: fastcgi buffer requests for fastcgi by default
  modules/caddyhttp/reverseproxy/reverseproxy.go
Labels: bug :lady_beetle:

#6803 chore: update quic-go to v0.49.0
  go.mod
  go.sum
Labels: dependencies :chains:

#6807 chore: don't use deprecated `archives.format_overrides.format`
  .goreleaser.yml
Labels: CI/CD :nut_and_bolt:

#6809 feat: automatically set GOMEMLIMIT
  cmd/main.go
  go.mod
  go.sum
Labels: optimization :chart_with_downwards_trend:

#6806 reverse_proxy: re-add healthy upstreams metric
  modules/caddyhttp/reverseproxy/metrics.go
  modules/caddyhttp/reverseproxy/reverseproxy.go
Labels: bug :lady_beetle:, under review :monocle_face:
